/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminAPIKeyListResult,
  AdminClientListResult,
  AdminClientResult,
  AdminOperator,
  AdminOperatorListResult,
  CreateOperatorRequest,
  ErrorResponse,
  GetAdminApiKeysOperatorOperatorIdParams,
  GetAdminApiKeysParams,
  GlobalAPIKeyStatsResult,
  OperatorAPIKeyStatsResult,
  SuccessResult,
  SupportBundleResult,
  UpdateAdminClientRequest,
  UpdateOperatorRequest
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetAdminApiKeysUrl = (params?: GetAdminApiKeysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/api-keys?${stringifiedParams}` : `/admin/api-keys`
}

/**
 * Lists all API keys across all operators (super admin only)
 * @summary List all API keys
 */
export const getAdminApiKeys = async (params?: GetAdminApiKeysParams, options?: Parameters<typeof customAxios>[1]): Promise<AdminAPIKeyListResult> => {

  return customAxios<AdminAPIKeyListResult>(getGetAdminApiKeysUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminApiKeysQueryKey = (params?: GetAdminApiKeysParams,) => {
    return [
    `/admin/api-keys`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminApiKeysQueryOptions = <TData = Awaited<ReturnType<typeof getAdminApiKeys>>, TError = ErrorResponse>(params?: GetAdminApiKeysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeys>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminApiKeysQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminApiKeys>>> = ({ signal }) => getAdminApiKeys(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeys>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminApiKeysQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminApiKeys>>>
export type GetAdminApiKeysQueryError = ErrorResponse


/**
 * @summary List all API keys
 */

export function useGetAdminApiKeys<TData = Awaited<ReturnType<typeof getAdminApiKeys>>, TError = ErrorResponse>(
 params?: GetAdminApiKeysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeys>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminApiKeysQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetAdminApiKeysOperatorOperatorIdUrl = (operatorId: string,
    params?: GetAdminApiKeysOperatorOperatorIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/admin/api-keys/operator/${operatorId}?${stringifiedParams}` : `/admin/api-keys/operator/${operatorId}`
}

/**
 * Lists all API keys for a specific operator (super admin only)
 * @summary List operator API keys
 */
export const getAdminApiKeysOperatorOperatorId = async (operatorId: string,
    params?: GetAdminApiKeysOperatorOperatorIdParams, options?: Parameters<typeof customAxios>[1]): Promise<AdminAPIKeyListResult> => {

  return customAxios<AdminAPIKeyListResult>(getGetAdminApiKeysOperatorOperatorIdUrl(operatorId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminApiKeysOperatorOperatorIdQueryKey = (operatorId: string,
    params?: GetAdminApiKeysOperatorOperatorIdParams,) => {
    return [
    `/admin/api-keys/operator/${operatorId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAdminApiKeysOperatorOperatorIdQueryOptions = <TData = Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>, TError = ErrorResponse>(operatorId: string,
    params?: GetAdminApiKeysOperatorOperatorIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminApiKeysOperatorOperatorIdQueryKey(operatorId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>> = ({ signal }) => getAdminApiKeysOperatorOperatorId(operatorId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: operatorId !== null && operatorId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminApiKeysOperatorOperatorIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>>
export type GetAdminApiKeysOperatorOperatorIdQueryError = ErrorResponse


/**
 * @summary List operator API keys
 */

export function useGetAdminApiKeysOperatorOperatorId<TData = Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>, TError = ErrorResponse>(
 operatorId: string,
    params?: GetAdminApiKeysOperatorOperatorIdParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysOperatorOperatorId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminApiKeysOperatorOperatorIdQueryOptions(operatorId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetAdminApiKeysStatsUrl = () => {




  return `/admin/api-keys/stats`
}

/**
 * Returns global API key statistics (super admin only)
 * @summary Get global API key stats
 */
export const getAdminApiKeysStats = async ( options?: Parameters<typeof customAxios>[1]): Promise<GlobalAPIKeyStatsResult> => {

  return customAxios<GlobalAPIKeyStatsResult>(getGetAdminApiKeysStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminApiKeysStatsQueryKey = () => {
    return [
    `/admin/api-keys/stats`
    ] as const;
    }


export const getGetAdminApiKeysStatsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminApiKeysStats>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStats>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminApiKeysStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminApiKeysStats>>> = ({ signal }) => getAdminApiKeysStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminApiKeysStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminApiKeysStats>>>
export type GetAdminApiKeysStatsQueryError = ErrorResponse


/**
 * @summary Get global API key stats
 */

export function useGetAdminApiKeysStats<TData = Awaited<ReturnType<typeof getAdminApiKeysStats>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStats>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminApiKeysStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetAdminApiKeysStatsOperatorOperatorIdUrl = (operatorId: string,) => {




  return `/admin/api-keys/stats/operator/${operatorId}`
}

/**
 * Returns API key statistics for a specific operator (super admin only)
 * @summary Get operator API key stats
 */
export const getAdminApiKeysStatsOperatorOperatorId = async (operatorId: string, options?: Parameters<typeof customAxios>[1]): Promise<OperatorAPIKeyStatsResult> => {

  return customAxios<OperatorAPIKeyStatsResult>(getGetAdminApiKeysStatsOperatorOperatorIdUrl(operatorId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminApiKeysStatsOperatorOperatorIdQueryKey = (operatorId: string,) => {
    return [
    `/admin/api-keys/stats/operator/${operatorId}`
    ] as const;
    }


export const getGetAdminApiKeysStatsOperatorOperatorIdQueryOptions = <TData = Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>, TError = ErrorResponse>(operatorId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminApiKeysStatsOperatorOperatorIdQueryKey(operatorId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>> = ({ signal }) => getAdminApiKeysStatsOperatorOperatorId(operatorId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: operatorId !== null && operatorId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminApiKeysStatsOperatorOperatorIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>>
export type GetAdminApiKeysStatsOperatorOperatorIdQueryError = ErrorResponse


/**
 * @summary Get operator API key stats
 */

export function useGetAdminApiKeysStatsOperatorOperatorId<TData = Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>, TError = ErrorResponse>(
 operatorId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminApiKeysStatsOperatorOperatorId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminApiKeysStatsOperatorOperatorIdQueryOptions(operatorId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAdminApiKeysKeyIdUrl = (keyId: string,) => {




  return `/admin/api-keys/${keyId}`
}

/**
 * Force revokes an API key for any operator (super admin only)
 * @summary Force revoke API key
 */
export const deleteAdminApiKeysKeyId = async (keyId: string, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

  return customAxios<SuccessResult>(getDeleteAdminApiKeysKeyIdUrl(keyId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAdminApiKeysKeyIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>, TError,{keyId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>, TError,{keyId: string}, TContext> => {

const mutationKey = ['deleteAdminApiKeysKeyId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>, {keyId: string}> = (props) => {
          const {keyId} = props ?? {};

          return  deleteAdminApiKeysKeyId(keyId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminApiKeysKeyIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>>

    export type DeleteAdminApiKeysKeyIdMutationError = ErrorResponse

    /**
 * @summary Force revoke API key
 */
export const useDeleteAdminApiKeysKeyId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>, TError,{keyId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminApiKeysKeyId>>,
        TError,
        {keyId: string},
        TContext
      > => {
      return useMutation(getDeleteAdminApiKeysKeyIdMutationOptions(options));
    }
    export const getGetAdminClientsUrl = () => {




  return `/admin/clients`
}

/**
 * Returns all OAuth clients (super_admin only)
 * @summary List admin clients
 */
export const getAdminClients = async ( options?: Parameters<typeof customAxios>[1]): Promise<AdminClientListResult> => {

  return customAxios<AdminClientListResult>(getGetAdminClientsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminClientsQueryKey = () => {
    return [
    `/admin/clients`
    ] as const;
    }


export const getGetAdminClientsQueryOptions = <TData = Awaited<ReturnType<typeof getAdminClients>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminClients>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminClientsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminClients>>> = ({ signal }) => getAdminClients({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminClients>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminClientsQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminClients>>>
export type GetAdminClientsQueryError = ErrorResponse


/**
 * @summary List admin clients
 */

export function useGetAdminClients<TData = Awaited<ReturnType<typeof getAdminClients>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminClients>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminClientsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetAdminClientsClientIdUrl = (clientId: string,) => {




  return `/admin/clients/${clientId}`
}

/**
 * Returns a single OAuth client by ID (super_admin only)
 * @summary Get admin client
 */
export const getAdminClientsClientId = async (clientId: string, options?: Parameters<typeof customAxios>[1]): Promise<AdminClientResult> => {

  return customAxios<AdminClientResult>(getGetAdminClientsClientIdUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminClientsClientIdQueryKey = (clientId: string,) => {
    return [
    `/admin/clients/${clientId}`
    ] as const;
    }


export const getGetAdminClientsClientIdQueryOptions = <TData = Awaited<ReturnType<typeof getAdminClientsClientId>>, TError = ErrorResponse>(clientId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminClientsClientId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminClientsClientIdQueryKey(clientId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminClientsClientId>>> = ({ signal }) => getAdminClientsClientId(clientId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: clientId !== null && clientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminClientsClientId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminClientsClientIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminClientsClientId>>>
export type GetAdminClientsClientIdQueryError = ErrorResponse


/**
 * @summary Get admin client
 */

export function useGetAdminClientsClientId<TData = Awaited<ReturnType<typeof getAdminClientsClientId>>, TError = ErrorResponse>(
 clientId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminClientsClientId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminClientsClientIdQueryOptions(clientId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAdminClientsClientIdUrl = (clientId: string,) => {




  return `/admin/clients/${clientId}`
}

/**
 * Revokes a client (super_admin only)
 * @summary Delete admin client
 */
export const deleteAdminClientsClientId = async (clientId: string, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

  return customAxios<SuccessResult>(getDeleteAdminClientsClientIdUrl(clientId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAdminClientsClientIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminClientsClientId>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAdminClientsClientId>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['deleteAdminClientsClientId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAdminClientsClientId>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  deleteAdminClientsClientId(clientId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAdminClientsClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAdminClientsClientId>>>

    export type DeleteAdminClientsClientIdMutationError = ErrorResponse

    /**
 * @summary Delete admin client
 */
export const useDeleteAdminClientsClientId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAdminClientsClientId>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAdminClientsClientId>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getDeleteAdminClientsClientIdMutationOptions(options));
    }
    export const getPatchAdminClientsClientIdUrl = (clientId: string,) => {




  return `/admin/clients/${clientId}`
}

/**
 * Updates mutable client fields (super_admin only)
 * @summary Update admin client
 */
export const patchAdminClientsClientId = async (clientId: string,
    updateAdminClientRequest: UpdateAdminClientRequest, options?: Parameters<typeof customAxios>[1]): Promise<AdminClientResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<AdminClientResult>(getPatchAdminClientsClientIdUrl(clientId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAdminClientRequest)
  }
);}





export const getPatchAdminClientsClientIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminClientsClientId>>, TError,{clientId: string;data: UpdateAdminClientRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAdminClientsClientId>>, TError,{clientId: string;data: UpdateAdminClientRequest}, TContext> => {

const mutationKey = ['patchAdminClientsClientId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAdminClientsClientId>>, {clientId: string;data: UpdateAdminClientRequest}> = (props) => {
          const {clientId,data} = props ?? {};

          return  patchAdminClientsClientId(clientId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAdminClientsClientIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAdminClientsClientId>>>
    export type PatchAdminClientsClientIdMutationBody = UpdateAdminClientRequest
    export type PatchAdminClientsClientIdMutationError = ErrorResponse

    /**
 * @summary Update admin client
 */
export const usePatchAdminClientsClientId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAdminClientsClientId>>, TError,{clientId: string;data: UpdateAdminClientRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAdminClientsClientId>>,
        TError,
        {clientId: string;data: UpdateAdminClientRequest},
        TContext
      > => {
      return useMutation(getPatchAdminClientsClientIdMutationOptions(options));
    }
    export const getPostAdminClientsClientIdRotateKeyUrl = (clientId: string,) => {




  return `/admin/clients/${clientId}/rotate-key`
}

/**
 * Rotates the signing key with a 24-hour grace period (super_admin only)
 * @summary Rotate admin client key
 */
export const postAdminClientsClientIdRotateKey = async (clientId: string, options?: Parameters<typeof customAxios>[1]): Promise<AdminClientResult> => {

  return customAxios<AdminClientResult>(getPostAdminClientsClientIdRotateKeyUrl(clientId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAdminClientsClientIdRotateKeyMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>, TError,{clientId: string}, TContext> => {

const mutationKey = ['postAdminClientsClientIdRotateKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>, {clientId: string}> = (props) => {
          const {clientId} = props ?? {};

          return  postAdminClientsClientIdRotateKey(clientId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAdminClientsClientIdRotateKeyMutationResult = NonNullable<Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>>

    export type PostAdminClientsClientIdRotateKeyMutationError = ErrorResponse

    /**
 * @summary Rotate admin client key
 */
export const usePostAdminClientsClientIdRotateKey = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>, TError,{clientId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAdminClientsClientIdRotateKey>>,
        TError,
        {clientId: string},
        TContext
      > => {
      return useMutation(getPostAdminClientsClientIdRotateKeyMutationOptions(options));
    }
    export const getGetAdminSupportBundleUrl = () => {




  return `/admin/support-bundle`
}

/**
 * Returns a diagnostic support bundle with runtime and DB stats (super_admin only)
 * @summary Get support bundle
 */
export const getAdminSupportBundle = async ( options?: Parameters<typeof customAxios>[1]): Promise<SupportBundleResult> => {

  return customAxios<SupportBundleResult>(getGetAdminSupportBundleUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAdminSupportBundleQueryKey = () => {
    return [
    `/admin/support-bundle`
    ] as const;
    }


export const getGetAdminSupportBundleQueryOptions = <TData = Awaited<ReturnType<typeof getAdminSupportBundle>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportBundle>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAdminSupportBundleQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminSupportBundle>>> = ({ signal }) => getAdminSupportBundle({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportBundle>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAdminSupportBundleQueryResult = NonNullable<Awaited<ReturnType<typeof getAdminSupportBundle>>>
export type GetAdminSupportBundleQueryError = ErrorResponse


/**
 * @summary Get support bundle
 */

export function useGetAdminSupportBundle<TData = Awaited<ReturnType<typeof getAdminSupportBundle>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAdminSupportBundle>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAdminSupportBundleQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetAuthAdminOperatorsUrl = () => {




  return `/auth/admin/operators`
}

/**
 * Lists all operators in the system (super_admin only)
 * @summary List operators
 */
export const getAuthAdminOperators = async ( options?: Parameters<typeof customAxios>[1]): Promise<AdminOperatorListResult> => {

  return customAxios<AdminOperatorListResult>(getGetAuthAdminOperatorsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthAdminOperatorsQueryKey = () => {
    return [
    `/auth/admin/operators`
    ] as const;
    }


export const getGetAuthAdminOperatorsQueryOptions = <TData = Awaited<ReturnType<typeof getAuthAdminOperators>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperators>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthAdminOperatorsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthAdminOperators>>> = ({ signal }) => getAuthAdminOperators({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperators>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthAdminOperatorsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthAdminOperators>>>
export type GetAuthAdminOperatorsQueryError = ErrorResponse


/**
 * @summary List operators
 */

export function useGetAuthAdminOperators<TData = Awaited<ReturnType<typeof getAuthAdminOperators>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperators>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthAdminOperatorsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthAdminOperatorsUrl = () => {




  return `/auth/admin/operators`
}

/**
 * Creates a new operator (super_admin only)
 * @summary Create operator
 */
export const postAuthAdminOperators = async (createOperatorRequest: CreateOperatorRequest, options?: Parameters<typeof customAxios>[1]): Promise<AdminOperator> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<AdminOperator>(getPostAuthAdminOperatorsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createOperatorRequest)
  }
);}





export const getPostAuthAdminOperatorsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminOperators>>, TError,{data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminOperators>>, TError,{data: CreateOperatorRequest}, TContext> => {

const mutationKey = ['postAuthAdminOperators'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthAdminOperators>>, {data: CreateOperatorRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthAdminOperators(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthAdminOperatorsMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthAdminOperators>>>
    export type PostAuthAdminOperatorsMutationBody = CreateOperatorRequest
    export type PostAuthAdminOperatorsMutationError = ErrorResponse

    /**
 * @summary Create operator
 */
export const usePostAuthAdminOperators = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminOperators>>, TError,{data: CreateOperatorRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthAdminOperators>>,
        TError,
        {data: CreateOperatorRequest},
        TContext
      > => {
      return useMutation(getPostAuthAdminOperatorsMutationOptions(options));
    }
    export const getGetAuthAdminOperatorsIdUrl = (id: string,) => {




  return `/auth/admin/operators/${id}`
}

/**
 * Returns a single operator by ID (super_admin only)
 * @summary Get operator
 */
export const getAuthAdminOperatorsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<AdminOperator> => {

  return customAxios<AdminOperator>(getGetAuthAdminOperatorsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthAdminOperatorsIdQueryKey = (id: string,) => {
    return [
    `/auth/admin/operators/${id}`
    ] as const;
    }


export const getGetAuthAdminOperatorsIdQueryOptions = <TData = Awaited<ReturnType<typeof getAuthAdminOperatorsId>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperatorsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthAdminOperatorsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthAdminOperatorsId>>> = ({ signal }) => getAuthAdminOperatorsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperatorsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthAdminOperatorsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthAdminOperatorsId>>>
export type GetAuthAdminOperatorsIdQueryError = ErrorResponse


/**
 * @summary Get operator
 */

export function useGetAuthAdminOperatorsId<TData = Awaited<ReturnType<typeof getAuthAdminOperatorsId>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthAdminOperatorsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthAdminOperatorsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAuthAdminOperatorsIdUrl = (id: string,) => {




  return `/auth/admin/operators/${id}`
}

/**
 * Deletes an operator. Cannot delete yourself or the last super_admin
 * @summary Delete operator
 */
export const deleteAuthAdminOperatorsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

  return customAxios<SuccessResult>(getDeleteAuthAdminOperatorsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAuthAdminOperatorsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAuthAdminOperatorsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAuthAdminOperatorsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAuthAdminOperatorsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>>

    export type DeleteAuthAdminOperatorsIdMutationError = ErrorResponse

    /**
 * @summary Delete operator
 */
export const useDeleteAuthAdminOperatorsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAuthAdminOperatorsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteAuthAdminOperatorsIdMutationOptions(options));
    }
    export const getPatchAuthAdminOperatorsIdUrl = (id: string,) => {




  return `/auth/admin/operators/${id}`
}

/**
 * Updates mutable operator fields (super_admin only)
 * @summary Update operator
 */
export const patchAuthAdminOperatorsId = async (id: string,
    updateOperatorRequest: UpdateOperatorRequest, options?: Parameters<typeof customAxios>[1]): Promise<AdminOperator> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<AdminOperator>(getPatchAuthAdminOperatorsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateOperatorRequest)
  }
);}





export const getPatchAuthAdminOperatorsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>, TError,{id: string;data: UpdateOperatorRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>, TError,{id: string;data: UpdateOperatorRequest}, TContext> => {

const mutationKey = ['patchAuthAdminOperatorsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>, {id: string;data: UpdateOperatorRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAuthAdminOperatorsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAuthAdminOperatorsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>>
    export type PatchAuthAdminOperatorsIdMutationBody = UpdateOperatorRequest
    export type PatchAuthAdminOperatorsIdMutationError = ErrorResponse

    /**
 * @summary Update operator
 */
export const usePatchAuthAdminOperatorsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>, TError,{id: string;data: UpdateOperatorRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAuthAdminOperatorsId>>,
        TError,
        {id: string;data: UpdateOperatorRequest},
        TContext
      > => {
      return useMutation(getPatchAuthAdminOperatorsIdMutationOptions(options));
    }
