/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  MessageResult,
  OrganizationMember,
  OrganizationMemberListResult,
  UpdateMemberRoleRequest
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetOrganizationsIdMembersUrl = (id: string,) => {




  return `/organizations/${id}/members`
}

/**
 * Returns all members of an organization
 * @summary List organization members
 */
export const getOrganizationsIdMembers = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<OrganizationMemberListResult> => {

  return customAxios<OrganizationMemberListResult>(getGetOrganizationsIdMembersUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsIdMembersQueryKey = (id: string,) => {
    return [
    `/organizations/${id}/members`
    ] as const;
    }


export const getGetOrganizationsIdMembersQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsIdMembers>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembers>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsIdMembersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsIdMembers>>> = ({ signal }) => getOrganizationsIdMembers(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsIdMembersQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsIdMembers>>>
export type GetOrganizationsIdMembersQueryError = ErrorResponse


/**
 * @summary List organization members
 */

export function useGetOrganizationsIdMembers<TData = Awaited<ReturnType<typeof getOrganizationsIdMembers>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembers>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsIdMembersQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetOrganizationsIdMembersMemberIdUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}`
}

/**
 * Returns a single organization member by ID
 * @summary Get organization member
 */
export const getOrganizationsIdMembersMemberId = async (id: string,
    memberId: string, options?: Parameters<typeof customAxios>[1]): Promise<OrganizationMember> => {

  return customAxios<OrganizationMember>(getGetOrganizationsIdMembersMemberIdUrl(id,memberId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsIdMembersMemberIdQueryKey = (id: string,
    memberId: string,) => {
    return [
    `/organizations/${id}/members/${memberId}`
    ] as const;
    }


export const getGetOrganizationsIdMembersMemberIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>, TError = ErrorResponse>(id: string,
    memberId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsIdMembersMemberIdQueryKey(id,memberId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>> = ({ signal }) => getOrganizationsIdMembersMemberId(id,memberId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && memberId !== null && memberId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsIdMembersMemberIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>>
export type GetOrganizationsIdMembersMemberIdQueryError = ErrorResponse


/**
 * @summary Get organization member
 */

export function useGetOrganizationsIdMembersMemberId<TData = Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>, TError = ErrorResponse>(
 id: string,
    memberId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdMembersMemberId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsIdMembersMemberIdQueryOptions(id,memberId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteOrganizationsIdMembersMemberIdUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}`
}

/**
 * Removes a member from an organization. Cannot remove the last super_admin or yourself
 * @summary Remove organization member
 */
export const deleteOrganizationsIdMembersMemberId = async (id: string,
    memberId: string, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getDeleteOrganizationsIdMembersMemberIdUrl(id,memberId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteOrganizationsIdMembersMemberIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>, TError,{id: string;memberId: string}, TContext> => {

const mutationKey = ['deleteOrganizationsIdMembersMemberId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>, {id: string;memberId: string}> = (props) => {
          const {id,memberId} = props ?? {};

          return  deleteOrganizationsIdMembersMemberId(id,memberId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrganizationsIdMembersMemberIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>>

    export type DeleteOrganizationsIdMembersMemberIdMutationError = ErrorResponse

    /**
 * @summary Remove organization member
 */
export const useDeleteOrganizationsIdMembersMemberId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrganizationsIdMembersMemberId>>,
        TError,
        {id: string;memberId: string},
        TContext
      > => {
      return useMutation(getDeleteOrganizationsIdMembersMemberIdMutationOptions(options));
    }
    export const getPostOrganizationsIdMembersMemberIdReinstateUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}/reinstate`
}

/**
 * Reinstates a suspended organization member
 * @summary Reinstate member
 */
export const postOrganizationsIdMembersMemberIdReinstate = async (id: string,
    memberId: string, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getPostOrganizationsIdMembersMemberIdReinstateUrl(id,memberId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostOrganizationsIdMembersMemberIdReinstateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>, TError,{id: string;memberId: string}, TContext> => {

const mutationKey = ['postOrganizationsIdMembersMemberIdReinstate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>, {id: string;memberId: string}> = (props) => {
          const {id,memberId} = props ?? {};

          return  postOrganizationsIdMembersMemberIdReinstate(id,memberId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrganizationsIdMembersMemberIdReinstateMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>>

    export type PostOrganizationsIdMembersMemberIdReinstateMutationError = ErrorResponse

    /**
 * @summary Reinstate member
 */
export const usePostOrganizationsIdMembersMemberIdReinstate = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdReinstate>>,
        TError,
        {id: string;memberId: string},
        TContext
      > => {
      return useMutation(getPostOrganizationsIdMembersMemberIdReinstateMutationOptions(options));
    }
    export const getPatchOrganizationsIdMembersMemberIdRoleUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}/role`
}

/**
 * Updates a member's role. Cannot change role to super_admin
 * @summary Update member role
 */
export const patchOrganizationsIdMembersMemberIdRole = async (id: string,
    memberId: string,
    updateMemberRoleRequest: UpdateMemberRoleRequest, options?: Parameters<typeof customAxios>[1]): Promise<OrganizationMember> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<OrganizationMember>(getPatchOrganizationsIdMembersMemberIdRoleUrl(id,memberId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateMemberRoleRequest)
  }
);}





export const getPatchOrganizationsIdMembersMemberIdRoleMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>, TError,{id: string;memberId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>, TError,{id: string;memberId: string;data: UpdateMemberRoleRequest}, TContext> => {

const mutationKey = ['patchOrganizationsIdMembersMemberIdRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>, {id: string;memberId: string;data: UpdateMemberRoleRequest}> = (props) => {
          const {id,memberId,data} = props ?? {};

          return  patchOrganizationsIdMembersMemberIdRole(id,memberId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchOrganizationsIdMembersMemberIdRoleMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>>
    export type PatchOrganizationsIdMembersMemberIdRoleMutationBody = UpdateMemberRoleRequest
    export type PatchOrganizationsIdMembersMemberIdRoleMutationError = ErrorResponse

    /**
 * @summary Update member role
 */
export const usePatchOrganizationsIdMembersMemberIdRole = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>, TError,{id: string;memberId: string;data: UpdateMemberRoleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchOrganizationsIdMembersMemberIdRole>>,
        TError,
        {id: string;memberId: string;data: UpdateMemberRoleRequest},
        TContext
      > => {
      return useMutation(getPatchOrganizationsIdMembersMemberIdRoleMutationOptions(options));
    }
    export const getPostOrganizationsIdMembersMemberIdSuspendUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}/suspend`
}

/**
 * Suspends an organization member
 * @summary Suspend member
 */
export const postOrganizationsIdMembersMemberIdSuspend = async (id: string,
    memberId: string, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getPostOrganizationsIdMembersMemberIdSuspendUrl(id,memberId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostOrganizationsIdMembersMemberIdSuspendMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>, TError,{id: string;memberId: string}, TContext> => {

const mutationKey = ['postOrganizationsIdMembersMemberIdSuspend'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>, {id: string;memberId: string}> = (props) => {
          const {id,memberId} = props ?? {};

          return  postOrganizationsIdMembersMemberIdSuspend(id,memberId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrganizationsIdMembersMemberIdSuspendMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>>

    export type PostOrganizationsIdMembersMemberIdSuspendMutationError = ErrorResponse

    /**
 * @summary Suspend member
 */
export const usePostOrganizationsIdMembersMemberIdSuspend = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdSuspend>>,
        TError,
        {id: string;memberId: string},
        TContext
      > => {
      return useMutation(getPostOrganizationsIdMembersMemberIdSuspendMutationOptions(options));
    }
    export const getPostOrganizationsIdMembersMemberIdTransferUrl = (id: string,
    memberId: string,) => {




  return `/organizations/${id}/members/${memberId}/transfer`
}

/**
 * Transfers organization ownership to another member
 * @summary Transfer ownership
 */
export const postOrganizationsIdMembersMemberIdTransfer = async (id: string,
    memberId: string, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getPostOrganizationsIdMembersMemberIdTransferUrl(id,memberId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostOrganizationsIdMembersMemberIdTransferMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>, TError,{id: string;memberId: string}, TContext> => {

const mutationKey = ['postOrganizationsIdMembersMemberIdTransfer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>, {id: string;memberId: string}> = (props) => {
          const {id,memberId} = props ?? {};

          return  postOrganizationsIdMembersMemberIdTransfer(id,memberId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrganizationsIdMembersMemberIdTransferMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>>

    export type PostOrganizationsIdMembersMemberIdTransferMutationError = ErrorResponse

    /**
 * @summary Transfer ownership
 */
export const usePostOrganizationsIdMembersMemberIdTransfer = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>, TError,{id: string;memberId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postOrganizationsIdMembersMemberIdTransfer>>,
        TError,
        {id: string;memberId: string},
        TContext
      > => {
      return useMutation(getPostOrganizationsIdMembersMemberIdTransferMutationOptions(options));
    }
