// Re-export domain types and utilities
export * from './domain';

// Re-export vyzorServer
export * from './vyzorServer';

// Re-export generated endpoint function objects (orval — axios mode).
export { getAuth } from './generated/auth/auth';
export { getMfa } from './generated/mfa/mfa';
export { getDevices } from './generated/devices/devices';
export { getCommands } from './generated/commands/commands';
export { getUpdates } from './generated/updates/updates';
export { getInbox } from './generated/inbox/inbox';
export { getOrganizations } from './generated/organizations/organizations';
export { getMembers } from './generated/members/members';
export { getInvitations } from './generated/invitations/invitations';
export { getSettings } from './generated/settings/settings';
export { getSessions } from './generated/sessions/sessions';
export { getAdmin } from './generated/admin/admin';
export { getApiKeys } from './generated/api-keys/api-keys';
export { getClientCredentials } from './generated/client-credentials/client-credentials';
export { getServiceAccounts } from './generated/service-accounts/service-accounts';
export { getContactPoints } from './generated/contact-points/contact-points';
export { getAlerts } from './generated/alerts/alerts';
export { getDashboard } from './generated/dashboard/dashboard';
export { getDiagnostics } from './generated/diagnostics/diagnostics';
export { getConnections } from './generated/connections/connections';
export { getTelemetry } from './generated/telemetry/telemetry';
export { getUpdater } from './generated/updater/updater';

// GraphQL: generated typed documents + the executor bridge over graphqlClient.
export * as generatedGraphql from './generated/graphql';
export { query as gqlQuery, mutate as gqlMutate, execute as gqlExecute } from './generated/graphql/executor';

// Wire DTO types (spec-derived). The react-query generated hooks
// (apps/VyzoriX_web/src/generated-rq) import these directly. The three names
// that collide with domain types are excluded here; the domain versions
// (camelCase) are re-exported under their own names below.
export type {
  APIKey,
  APIKeyListResult,
  APIKeyWithSecret,
  AdminAPIKey,
  AdminAPIKeyListResult,
  AdminClient,
  AdminClientListResult,
  AdminClientResult,
  AdminOperator,
  AdminOperatorListResult,
  AlertEvaluateResult,
  AlertHistoryEvent,
  AlertHistoryResult,
  AlertInstance,
  AlertInstanceLabels,
  AlertRule,
  AlertRuleListResult,
  AlertRuleRequest,
  Annotation,
  AnnotationListResult,
  AnnotationRequest,
  CancelVerificationRequest,
  ChannelStatusResult,
  ChannelSubscribeRequest,
  ChannelSubscribeResult,
  ChannelUnsubscribeResult,
  ClientCredential,
  ClientCredentialListResult,
  ClientSettings,
  CommandCancelResult,
  CommandConfirmRequest,
  CommandConfirmResult,
  CommandDispatchResult,
  CommandHistoryEntry,
  CommandHistoryResult,
  CommandPendingResult,
  CommandRequest,
  CommandRequestArgs,
  CommandResponse,
  CommandRetryResult,
  CommandStatus,
  ConcurrentSessionsResult,
  ConfigVersion,
  ConfigVersionListResult,
  ConfigVersionRestoreResult,
  ConfigVersionRestoreResultSettings,
  ConfigVersionSnapshot,
  ConnectionListResult,
  ConnectionMetricsResult,
  ConnectionStatusResult,
  ContactPoint,
  ContactPointConfig,
  ContactPointListResult,
  ContactPointRequest,
  ContactPointRequestConfig,
  ContactPointTestResult,
  CreateAPIKeyRequest,
  CreateClientCredentialRequest,
  CreateInvitationRequest,
  CreateOperatorRequest,
  CreateOrganizationRequest,
  CreateServiceAccountRequest,
  CreateServiceAccountTokenRequest,
  CursorPaginationResult,
  DashboardStats,
  DeleteDevicesImeiParams,
  DeletedResult,
  DeviceConfirmRequest,
  DeviceConfirmResult,
  DeviceCountResult,
  DeviceDetailResult,
  DeviceDisconnectResult,
  DeviceEvent,
  DeviceEventData,
  DeviceEventListResult,
  DeviceFCMTokenRequest,
  DeviceInspectionResult,
  DeviceListItem,
  DeviceListResult,
  DeviceLogEvent,
  DeviceLogEventData,
  DeviceLogEventListResult,
  DeviceSettingsResult,
  DeviceSettingsResultMetadata,
  DeviceTagAddedResult,
  DeviceTagRemovedResult,
  DeviceTagsResult,
  DeviceTransferRequest,
  DeviceTransferResult,
  DeviceUpdateStatusRequest,
  DeviceUpdateStatusResponse,
  DiagnosticsConnectionInfo,
  DiagnosticsIdentityInfo,
  DiagnosticsRegistrationInfo,
  DiagnosticsSoftwareInfo,
  DiagnosticsTelemetryInfo,
  DownloadProgressRequest,
  DownloadProgressResult,
  EmailNotifications,
  EmailVerifyRequest,
  EmailVerifyResult,
  ErrorResponse,
  ErrorResponseFields,
  ForgotPasswordRequest,
  GetAdminApiKeysOperatorOperatorIdParams,
  GetAdminApiKeysParams,
  GetAlertsRulesIdHistoryParams,
  GetAnnotationsParams,
  GetAuthApiKeysParams,
  GetAuthPollVerificationParams,
  GetAuthResendVerificationParams,
  GetAuthVerifyEmailParams,
  GetCheckUpdateParams,
  GetConfigVersionsResourceParams,
  GetDashboardDeviceImeiCommandsParams,
  GetDashboardDeviceImeiEventsParams,
  GetDashboardDeviceImeiLogsParams,
  GetDashboardDeviceImeiMetricsExportParams,
  GetDashboardDeviceImeiMetricsParams,
  GetDashboardDeviceImeiTelemetryParams,
  GetDashboardDevicesOperatorParams,
  GetDashboardDevicesParams,
  GetDashboardEventsRecentParams,
  GetDashboardEventsTypesTypeParams,
  GetDeviceImeiTimelineParams,
  GetDeviceInboxParams,
  GetDevicesParams,
  GetOrganizationsIdInvitationsParams,
  GetTelemetryHistoryExportParams,
  GetTelemetryHistoryParams,
  GetTelemetryResponse,
  GetUpdatesChangelogParams,
  GetUpdatesExportParams,
  GetUpdatesHistoryParams,
  GetUpdatesVersionsParams,
  GlobalAPIKeyStatsResult,
  GlobalAPIKeyStatsResultRequestsByScope,
  InboxAckRequest,
  InboxAckResult,
  InboxEntryResponse,
  InboxListResult,
  InboxRequest,
  InboxResendResult,
  Invitation,
  InvitationByTokenResult,
  InvitationListResult,
  LockoutStatusResult,
  LoginRequest,
  LoginResult,
  LoginWithTokensResult,
  LogoutRequest,
  MFABackupCodeRequest,
  MFABackupCodeResult,
  MFADisableRequest,
  MFAEnableRequest,
  MFAEnableResult,
  MFAEnrollResult,
  MFAOperator,
  MFARegenerateResult,
  MFAStatusResult,
  MFAVerifyRequest,
  MFAVerifyResult,
  MFAVerifySetupRequest,
  MeResult,
  MessageResult,
  MetricAggregateResult,
  MetricStatsDTO,
  NotificationSettings,
  NotificationUpdateRequest,
  OperatorAPIKeyStatsResult,
  OperatorSettingsResult,
  OperatorSettingsResultLegacy,
  OperatorThresholds,
  Organization,
  OrganizationInfo,
  OrganizationListResult,
  OrganizationMember,
  OrganizationMemberListResult,
  OrganizationSettingsResult,
  PollVerificationResult,
  PostAuthOauthGithubParams,
  PostAuthOauthGoogleParams,
  PostChannelsUnsubscribeParams,
  PreferencesResult,
  PreferencesResultPreferences,
  PushNotifications,
  RefreshTokenRequest,
  RefreshTokenResult,
  RegisterRequest,
  RegisterResult,
  ResendVerificationRequest,
  ResetPasswordRequest,
  RevokeResult,
  RevokedResult,
  RotateServiceAccountTokenRequest,
  SelectOrganizationRequest,
  SelectOrganizationResult,
  ServiceAccount,
  ServiceAccountListResult,
  ServiceAccountToken,
  ServiceAccountTokenCreated,
  ServiceAccountTokenListResult,
  ServiceAccountTokenRotated,
  SessionInfo,
  SessionListResult,
  SetDeviceTagsRequest,
  SettingsResponseResult,
  SettingsResponseResultPreferences,
  SuccessResult,
  SupportBundleResult,
  TelemetryEntry,
  TelemetryEntryMetrics,
  TelemetryFrameDTO,
  TelemetryHistoryEntry,
  TelemetryHistoryQueryResult,
  TelemetryStatsDTO,
  TelemetryStatsResult,
  ThresholdUpdateRequest,
  ThresholdsResult,
  TimelineEventResult,
  TimelineEventResultData,
  TopOperatorStat,
  UpdateAPIKeyRequest,
  UpdateAdminClientRequest,
  UpdateCancelPushResult,
  UpdateChangelogEntryResult,
  UpdateChangelogResult,
  UpdateCheckerResult,
  UpdateClientCredentialRequest,
  UpdateDeviceSettingsRequest,
  UpdateDeviceSettingsRequestMetadata,
  UpdateDeviceStatusInfo,
  UpdateExportResult,
  UpdateFailedDevice,
  UpdateInboxEntryRequest,
  UpdateLatestVersionInfo,
  UpdateMemberRoleRequest,
  UpdateNameRequest,
  UpdateOperatorRequest,
  UpdateOrganizationRequest,
  UpdateOrganizationSettingsRequest,
  UpdatePushDetailDevice,
  UpdatePushDetailResult,
  UpdatePushDeviceCounts,
  UpdatePushHistoryDeviceCounts,
  UpdatePushHistoryEntry,
  UpdatePushHistoryListResult,
  UpdatePushRequest,
  UpdatePushResult,
  UpdateSettingsRequest,
  UpdateStatusResult,
  UpdateSyncResponse,
  UpdateSyncStatusInfo,
  UpdateSyncStatusResult,
  UpdateVersionListResult,
  UpdateVersionResponse,
  UpdaterCheckResult,
  UpdaterVersionManifestResult,
  UsageStatsCounts,
  UsageStatsSnapshot,
  UsageStatsSnapshotToggles,
  WebhookNotifications,
  WebhookSecretResult,
  WebhookTestRequest,
  WebhookTestResult,
} from './generated/vyzorixUpdateServerAPI.schemas';

// Domain (camelCase) versions of the colliding wire names, exported under
// distinct aliases — generated-rq and the SDK root own the wire names.
export type {
  DeviceStatus as DomainDeviceStatus,
  Pagination as DomainPagination,
  TimelineResult as DomainTimelineResult,
} from './domain';

