// Code generated by tooling/codegen/build_schemas.py from .cue files.
// DO NOT EDIT MANUALLY.

package schema

type CreateAPIKeyRequest struct {
	Name          string `json:"name"`
	Scope         string `json:"scope"`
	ExpiresInDays int    `json:"expires_in_days,omitempty"`
}

type UpdateAPIKeyRequest struct {
	Name  string `json:"name,omitempty"`
	Scope string `json:"scope,omitempty"`
}

type AdminClient struct {
	ID             string   `json:"id"`
	LastRequestAt  *int64   `json:"last_request_at,omitempty"`
	Name           string   `json:"name"`
	OperatorID     string   `json:"operator_id"`
	Platform       string   `json:"platform"`
	AllowedOrigins []string `json:"allowed_origins"`
	AllowedPaths   []string `json:"allowed_paths"`
	CreatedAt      int64    `json:"created_at"`
	RateLimit      int      `json:"rate_limit"`
	RequestCount   int64    `json:"request_count"`
	UpdatedAt      int64    `json:"updated_at"`
	IsActive       bool     `json:"is_active"`
}

type AdminClientListResult struct {
	Clients []AdminClient `json:"clients"`
	Total   int           `json:"total"`
}

type AdminClientResult struct {
	Client AdminClient `json:"client"`
}

type UpdateAdminClientRequest struct {
	Name           string   `json:"name,omitempty"`
	AllowedOrigins []string `json:"allowed_origins,omitempty"`
	AllowedPaths   []string `json:"allowed_paths,omitempty"`
	RateLimit      int      `json:"rate_limit,omitempty"`
	IsActive       bool     `json:"is_active,omitempty"`
}

type UpdatePushRequest struct {
	InstallType string   `json:"installType"`
	ScheduledAt *int64   `json:"scheduledAt,omitempty"`
	Version     string   `json:"version"`
	DeviceIDs   []string `json:"deviceIds"`
}

type OrganizationInfo struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

type SelectOrganizationRequest struct {
	OrganizationID string `json:"organization_id"`
}

type SelectOrganizationResult struct {
	OrganizationID   string `json:"organization_id"`
	OrganizationName string `json:"organization_name"`
	Role             string `json:"role"`
}

type DeviceThresholds struct {
	BufferCrit  int `json:"bufferCrit"`
	BufferWarn  int `json:"bufferWarn"`
	RiskCrit    int `json:"riskCrit"`
	RiskWarn    int `json:"riskWarn"`
	ThermalCrit int `json:"thermalCrit"`
	ThermalWarn int `json:"thermalWarn"`
}

type InboxRequest struct {
	AppVersion        string `json:"appVersion,omitempty"`
	DeviceClass       string `json:"deviceClass,omitempty"`
	DeviceName        string `json:"deviceName,omitempty"`
	FCMToken          string `json:"fcmToken"`
	FirebaseInstallID string `json:"firebaseInstallId"`
	IdempotencyKey    string `json:"idempotencyKey,omitempty"`
	IMEI              string `json:"imei"`
	Manufacturer      string `json:"manufacturer,omitempty"`
	Model             string `json:"model,omitempty"`
	OSVersion         string `json:"osVersion,omitempty"`
}

type DeviceConfirmRequest struct {
	CommandSecret string `json:"commandSecret"`
	IMEI          string `json:"imei"`
}

type InboxAckRequest struct {
	Action string `json:"action"`
	Notes  string `json:"notes,omitempty"`
}

type UpdateInboxEntryRequest struct {
	Notes string `json:"notes,omitempty"`
}

type EmailNotifications struct {
	CommandFailed       bool `json:"commandFailed"`
	DeviceOffline       bool `json:"deviceOffline"`
	DeviceOnline        bool `json:"deviceOnline"`
	RegistrationRequest bool `json:"registrationRequest"`
	ThresholdBreach     bool `json:"thresholdBreach"`
	UpdateAvailable     bool `json:"updateAvailable"`
}

type PushNotifications struct {
	CommandFailed       bool `json:"commandFailed"`
	DeviceOffline       bool `json:"deviceOffline"`
	DeviceOnline        bool `json:"deviceOnline"`
	RegistrationRequest bool `json:"registrationRequest"`
	ThresholdBreach     bool `json:"thresholdBreach"`
	UpdateAvailable     bool `json:"updateAvailable"`
}

type WebhookNotifications struct {
	Secret  string   `json:"secret,omitempty"`
	URL     string   `json:"url"`
	Types   []string `json:"types"`
	Enabled bool     `json:"enabled"`
}

type NotificationSettings struct {
	Email    EmailNotifications   `json:"email"`
	Push     PushNotifications    `json:"push"`
	Webhook  WebhookNotifications `json:"webhook"`
	Channels []string             `json:"channels"`
	Enabled  bool                 `json:"enabled"`
}

type ClientSettings struct {
	DeviceID             string `json:"deviceId"`
	ServerURL            string `json:"serverUrl"`
	LogBufferLimit       int    `json:"logBufferLimit"`
	RequestTimeoutMs     int    `json:"requestTimeoutMs"`
	SignalHistoryLimit   int    `json:"signalHistoryLimit"`
	AutoReconnect        bool   `json:"autoReconnect"`
	NotificationsEnabled bool   `json:"notificationsEnabled"`
	StrictHmac           bool   `json:"strictHmac"`
}

type OperatorSettingsResultLegacy struct {
	Client        *ClientSettings `json:"client,omitempty"`
	Email         string          `json:"email"`
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Role          string          `json:"role,omitempty"`
	EmailVerified bool            `json:"email_verified"`
	MFAEnabled    bool            `json:"mfa_enabled"`
}
