/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlertEvaluateResult,
  AlertHistoryResult,
  AlertRule,
  AlertRuleListResult,
  AlertRuleRequest,
  DeletedResult,
  ErrorResponse,
  GetAlertsRulesIdHistoryParams
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetAlertsRulesUrl = () => {




  return `/alerts/rules`
}

/**
 * Returns all org-scoped alert rules with their current instance states
 * @summary List alert rules
 */
export const getAlertsRules = async ( options?: Parameters<typeof customAxios>[1]): Promise<AlertRuleListResult> => {

  return customAxios<AlertRuleListResult>(getGetAlertsRulesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAlertsRulesQueryKey = () => {
    return [
    `/alerts/rules`
    ] as const;
    }


export const getGetAlertsRulesQueryOptions = <TData = Awaited<ReturnType<typeof getAlertsRules>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRules>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAlertsRulesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlertsRules>>> = ({ signal }) => getAlertsRules({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAlertsRules>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAlertsRulesQueryResult = NonNullable<Awaited<ReturnType<typeof getAlertsRules>>>
export type GetAlertsRulesQueryError = ErrorResponse


/**
 * @summary List alert rules
 */

export function useGetAlertsRules<TData = Awaited<ReturnType<typeof getAlertsRules>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRules>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAlertsRulesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAlertsRulesUrl = () => {




  return `/alerts/rules`
}

/**
 * Creates a new org-scoped alert rule. Validated before persistence
 * @summary Create alert rule
 */
export const postAlertsRules = async (alertRuleRequest: AlertRuleRequest, options?: Parameters<typeof customAxios>[1]): Promise<AlertRule> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<AlertRule>(getPostAlertsRulesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(alertRuleRequest)
  }
);}





export const getPostAlertsRulesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAlertsRules>>, TError,{data: AlertRuleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAlertsRules>>, TError,{data: AlertRuleRequest}, TContext> => {

const mutationKey = ['postAlertsRules'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAlertsRules>>, {data: AlertRuleRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAlertsRules(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAlertsRulesMutationResult = NonNullable<Awaited<ReturnType<typeof postAlertsRules>>>
    export type PostAlertsRulesMutationBody = AlertRuleRequest
    export type PostAlertsRulesMutationError = ErrorResponse

    /**
 * @summary Create alert rule
 */
export const usePostAlertsRules = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAlertsRules>>, TError,{data: AlertRuleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAlertsRules>>,
        TError,
        {data: AlertRuleRequest},
        TContext
      > => {
      return useMutation(getPostAlertsRulesMutationOptions(options));
    }
    export const getGetAlertsRulesIdUrl = (id: string,) => {




  return `/alerts/rules/${id}`
}

/**
 * Returns one alert rule with its current instance states
 * @summary Get alert rule
 */
export const getAlertsRulesId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<AlertRule> => {

  return customAxios<AlertRule>(getGetAlertsRulesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAlertsRulesIdQueryKey = (id: string,) => {
    return [
    `/alerts/rules/${id}`
    ] as const;
    }


export const getGetAlertsRulesIdQueryOptions = <TData = Awaited<ReturnType<typeof getAlertsRulesId>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAlertsRulesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlertsRulesId>>> = ({ signal }) => getAlertsRulesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAlertsRulesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAlertsRulesId>>>
export type GetAlertsRulesIdQueryError = ErrorResponse


/**
 * @summary Get alert rule
 */

export function useGetAlertsRulesId<TData = Awaited<ReturnType<typeof getAlertsRulesId>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAlertsRulesIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAlertsRulesIdUrl = (id: string,) => {




  return `/alerts/rules/${id}`
}

/**
 * Removes the rule and its instances
 * @summary Delete alert rule
 */
export const deleteAlertsRulesId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<DeletedResult> => {

  return customAxios<DeletedResult>(getDeleteAlertsRulesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAlertsRulesIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlertsRulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAlertsRulesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAlertsRulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAlertsRulesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAlertsRulesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAlertsRulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAlertsRulesId>>>

    export type DeleteAlertsRulesIdMutationError = ErrorResponse

    /**
 * @summary Delete alert rule
 */
export const useDeleteAlertsRulesId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAlertsRulesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAlertsRulesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteAlertsRulesIdMutationOptions(options));
    }
    export const getPatchAlertsRulesIdUrl = (id: string,) => {




  return `/alerts/rules/${id}`
}

/**
 * Replaces a rule's mutable fields. Disabling clears its instances
 * @summary Update alert rule
 */
export const patchAlertsRulesId = async (id: string,
    alertRuleRequest: AlertRuleRequest, options?: Parameters<typeof customAxios>[1]): Promise<AlertRule> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<AlertRule>(getPatchAlertsRulesIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(alertRuleRequest)
  }
);}





export const getPatchAlertsRulesIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAlertsRulesId>>, TError,{id: string;data: AlertRuleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAlertsRulesId>>, TError,{id: string;data: AlertRuleRequest}, TContext> => {

const mutationKey = ['patchAlertsRulesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAlertsRulesId>>, {id: string;data: AlertRuleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchAlertsRulesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAlertsRulesIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchAlertsRulesId>>>
    export type PatchAlertsRulesIdMutationBody = AlertRuleRequest
    export type PatchAlertsRulesIdMutationError = ErrorResponse

    /**
 * @summary Update alert rule
 */
export const usePatchAlertsRulesId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAlertsRulesId>>, TError,{id: string;data: AlertRuleRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAlertsRulesId>>,
        TError,
        {id: string;data: AlertRuleRequest},
        TContext
      > => {
      return useMutation(getPatchAlertsRulesIdMutationOptions(options));
    }
    export const getPostAlertsRulesIdEvaluateUrl = (id: string,) => {




  return `/alerts/rules/${id}/evaluate`
}

/**
 * Triggers evaluation on the rule's metric immediately
 * @summary Manually evaluate a rule
 */
export const postAlertsRulesIdEvaluate = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<AlertEvaluateResult> => {

  return customAxios<AlertEvaluateResult>(getPostAlertsRulesIdEvaluateUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAlertsRulesIdEvaluateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>, TError,{id: string}, TContext> => {

const mutationKey = ['postAlertsRulesIdEvaluate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postAlertsRulesIdEvaluate(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAlertsRulesIdEvaluateMutationResult = NonNullable<Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>>

    export type PostAlertsRulesIdEvaluateMutationError = ErrorResponse

    /**
 * @summary Manually evaluate a rule
 */
export const usePostAlertsRulesIdEvaluate = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAlertsRulesIdEvaluate>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostAlertsRulesIdEvaluateMutationOptions(options));
    }
    export const getGetAlertsRulesIdHistoryUrl = (id: string,
    params?: GetAlertsRulesIdHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/alerts/rules/${id}/history?${stringifiedParams}` : `/alerts/rules/${id}/history`
}

/**
 * Transition events for an org, optionally narrowed to one rule
 * @summary Alert history
 */
export const getAlertsRulesIdHistory = async (id: string,
    params?: GetAlertsRulesIdHistoryParams, options?: Parameters<typeof customAxios>[1]): Promise<AlertHistoryResult> => {

  return customAxios<AlertHistoryResult>(getGetAlertsRulesIdHistoryUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAlertsRulesIdHistoryQueryKey = (id: string,
    params?: GetAlertsRulesIdHistoryParams,) => {
    return [
    `/alerts/rules/${id}/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAlertsRulesIdHistoryQueryOptions = <TData = Awaited<ReturnType<typeof getAlertsRulesIdHistory>>, TError = ErrorResponse>(id: string,
    params?: GetAlertsRulesIdHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesIdHistory>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAlertsRulesIdHistoryQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAlertsRulesIdHistory>>> = ({ signal }) => getAlertsRulesIdHistory(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesIdHistory>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAlertsRulesIdHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof getAlertsRulesIdHistory>>>
export type GetAlertsRulesIdHistoryQueryError = ErrorResponse


/**
 * @summary Alert history
 */

export function useGetAlertsRulesIdHistory<TData = Awaited<ReturnType<typeof getAlertsRulesIdHistory>>, TError = ErrorResponse>(
 id: string,
    params?: GetAlertsRulesIdHistoryParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAlertsRulesIdHistory>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAlertsRulesIdHistoryQueryOptions(id,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






