/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  NotificationSettings,
  NotificationUpdateRequest,
  OperatorSettingsResult,
  OperatorSettingsResultLegacy,
  PreferencesResult,
  SettingsResponseResult,
  ThresholdUpdateRequest,
  ThresholdsResult,
  UpdateNameRequest,
  UpdateSettingsRequest,
  WebhookSecretResult,
  WebhookTestRequest,
  WebhookTestResult
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPatchAuthMeUrl = () => {




  return `/auth/me`
}

/**
 * Updates the current operator's display name
 * @summary Update operator name
 */
export const patchAuthMe = async (updateNameRequest: UpdateNameRequest, options?: Parameters<typeof customAxios>[1]): Promise<OperatorSettingsResultLegacy> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<OperatorSettingsResultLegacy>(getPatchAuthMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateNameRequest)
  }
);}





export const getPatchAuthMeMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthMe>>, TError,{data: UpdateNameRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchAuthMe>>, TError,{data: UpdateNameRequest}, TContext> => {

const mutationKey = ['patchAuthMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAuthMe>>, {data: UpdateNameRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchAuthMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAuthMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchAuthMe>>>
    export type PatchAuthMeMutationBody = UpdateNameRequest
    export type PatchAuthMeMutationError = ErrorResponse

    /**
 * @summary Update operator name
 */
export const usePatchAuthMe = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAuthMe>>, TError,{data: UpdateNameRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchAuthMe>>,
        TError,
        {data: UpdateNameRequest},
        TContext
      > => {
      return useMutation(getPatchAuthMeMutationOptions(options));
    }
    export const getGetMeNotificationsUrl = () => {




  return `/me/notifications`
}

/**
 * Returns the current operator's notification settings
 * @summary Get notification settings
 */
export const getMeNotifications = async ( options?: Parameters<typeof customAxios>[1]): Promise<NotificationSettings> => {

  return customAxios<NotificationSettings>(getGetMeNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeNotificationsQueryKey = () => {
    return [
    `/me/notifications`
    ] as const;
    }


export const getGetMeNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof getMeNotifications>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeNotifications>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeNotifications>>> = ({ signal }) => getMeNotifications({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeNotifications>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getMeNotifications>>>
export type GetMeNotificationsQueryError = ErrorResponse


/**
 * @summary Get notification settings
 */

export function useGetMeNotifications<TData = Awaited<ReturnType<typeof getMeNotifications>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeNotifications>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeNotificationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchMeNotificationsUrl = () => {




  return `/me/notifications`
}

/**
 * Updates the current operator's notification settings
 * @summary Update notification settings
 */
export const patchMeNotifications = async (notificationUpdateRequest: NotificationUpdateRequest, options?: Parameters<typeof customAxios>[1]): Promise<NotificationSettings> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<NotificationSettings>(getPatchMeNotificationsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(notificationUpdateRequest)
  }
);}





export const getPatchMeNotificationsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeNotifications>>, TError,{data: NotificationUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchMeNotifications>>, TError,{data: NotificationUpdateRequest}, TContext> => {

const mutationKey = ['patchMeNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMeNotifications>>, {data: NotificationUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchMeNotifications(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMeNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof patchMeNotifications>>>
    export type PatchMeNotificationsMutationBody = NotificationUpdateRequest
    export type PatchMeNotificationsMutationError = ErrorResponse

    /**
 * @summary Update notification settings
 */
export const usePatchMeNotifications = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeNotifications>>, TError,{data: NotificationUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchMeNotifications>>,
        TError,
        {data: NotificationUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchMeNotificationsMutationOptions(options));
    }
    export const getPostMeNotificationsWebhookRotateUrl = () => {




  return `/me/notifications/webhook/rotate`
}

/**
 * Generates a new webhook signing secret. The new secret is only returned once
 * @summary Rotate webhook secret
 */
export const postMeNotificationsWebhookRotate = async ( options?: Parameters<typeof customAxios>[1]): Promise<WebhookSecretResult> => {

  return customAxios<WebhookSecretResult>(getPostMeNotificationsWebhookRotateUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostMeNotificationsWebhookRotateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>, TError,void, TContext> => {

const mutationKey = ['postMeNotificationsWebhookRotate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>, void> = () => {


          return  postMeNotificationsWebhookRotate(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMeNotificationsWebhookRotateMutationResult = NonNullable<Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>>

    export type PostMeNotificationsWebhookRotateMutationError = ErrorResponse

    /**
 * @summary Rotate webhook secret
 */
export const usePostMeNotificationsWebhookRotate = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postMeNotificationsWebhookRotate>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostMeNotificationsWebhookRotateMutationOptions(options));
    }
    export const getPostMeNotificationsWebhookTestUrl = () => {




  return `/me/notifications/webhook/test`
}

/**
 * Sends a test payload to the configured webhook URL and reports the result
 * @summary Test webhook
 */
export const postMeNotificationsWebhookTest = async (webhookTestRequest: WebhookTestRequest, options?: Parameters<typeof customAxios>[1]): Promise<WebhookTestResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<WebhookTestResult>(getPostMeNotificationsWebhookTestUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(webhookTestRequest)
  }
);}





export const getPostMeNotificationsWebhookTestMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>, TError,{data: WebhookTestRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>, TError,{data: WebhookTestRequest}, TContext> => {

const mutationKey = ['postMeNotificationsWebhookTest'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>, {data: WebhookTestRequest}> = (props) => {
          const {data} = props ?? {};

          return  postMeNotificationsWebhookTest(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMeNotificationsWebhookTestMutationResult = NonNullable<Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>>
    export type PostMeNotificationsWebhookTestMutationBody = WebhookTestRequest
    export type PostMeNotificationsWebhookTestMutationError = ErrorResponse

    /**
 * @summary Test webhook
 */
export const usePostMeNotificationsWebhookTest = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>, TError,{data: WebhookTestRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postMeNotificationsWebhookTest>>,
        TError,
        {data: WebhookTestRequest},
        TContext
      > => {
      return useMutation(getPostMeNotificationsWebhookTestMutationOptions(options));
    }
    export const getGetMePreferencesUrl = () => {




  return `/me/preferences`
}

/**
 * Returns the current operator's UI preferences
 * @summary Get operator preferences
 */
export const getMePreferences = async ( options?: Parameters<typeof customAxios>[1]): Promise<PreferencesResult> => {

  return customAxios<PreferencesResult>(getGetMePreferencesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMePreferencesQueryKey = () => {
    return [
    `/me/preferences`
    ] as const;
    }


export const getGetMePreferencesQueryOptions = <TData = Awaited<ReturnType<typeof getMePreferences>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMePreferences>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMePreferencesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMePreferences>>> = ({ signal }) => getMePreferences({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMePreferences>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMePreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof getMePreferences>>>
export type GetMePreferencesQueryError = ErrorResponse


/**
 * @summary Get operator preferences
 */

export function useGetMePreferences<TData = Awaited<ReturnType<typeof getMePreferences>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMePreferences>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMePreferencesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchMePreferencesUrl = () => {




  return `/me/preferences`
}

/**
 * Updates the current operator's UI preferences
 * @summary Update operator preferences
 */
export const patchMePreferences = async (preferencesResult: PreferencesResult, options?: Parameters<typeof customAxios>[1]): Promise<PreferencesResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<PreferencesResult>(getPatchMePreferencesUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(preferencesResult)
  }
);}





export const getPatchMePreferencesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMePreferences>>, TError,{data: PreferencesResult}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchMePreferences>>, TError,{data: PreferencesResult}, TContext> => {

const mutationKey = ['patchMePreferences'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMePreferences>>, {data: PreferencesResult}> = (props) => {
          const {data} = props ?? {};

          return  patchMePreferences(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMePreferencesMutationResult = NonNullable<Awaited<ReturnType<typeof patchMePreferences>>>
    export type PatchMePreferencesMutationBody = PreferencesResult
    export type PatchMePreferencesMutationError = ErrorResponse

    /**
 * @summary Update operator preferences
 */
export const usePatchMePreferences = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMePreferences>>, TError,{data: PreferencesResult}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchMePreferences>>,
        TError,
        {data: PreferencesResult},
        TContext
      > => {
      return useMutation(getPatchMePreferencesMutationOptions(options));
    }
    export const getGetMeSettingsUrl = () => {




  return `/me/settings`
}

/**
 * Returns the current operator's settings
 * @summary Get operator settings
 */
export const getMeSettings = async ( options?: Parameters<typeof customAxios>[1]): Promise<OperatorSettingsResult> => {

  return customAxios<OperatorSettingsResult>(getGetMeSettingsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeSettingsQueryKey = () => {
    return [
    `/me/settings`
    ] as const;
    }


export const getGetMeSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getMeSettings>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeSettingsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeSettings>>> = ({ signal }) => getMeSettings({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getMeSettings>>>
export type GetMeSettingsQueryError = ErrorResponse


/**
 * @summary Get operator settings
 */

export function useGetMeSettings<TData = Awaited<ReturnType<typeof getMeSettings>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeSettingsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchMeSettingsUrl = () => {




  return `/me/settings`
}

/**
 * Updates the current operator's settings
 * @summary Update operator settings
 */
export const patchMeSettings = async (updateSettingsRequest: UpdateSettingsRequest, options?: Parameters<typeof customAxios>[1]): Promise<SettingsResponseResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SettingsResponseResult>(getPatchMeSettingsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateSettingsRequest)
  }
);}





export const getPatchMeSettingsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeSettings>>, TError,{data: UpdateSettingsRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchMeSettings>>, TError,{data: UpdateSettingsRequest}, TContext> => {

const mutationKey = ['patchMeSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMeSettings>>, {data: UpdateSettingsRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchMeSettings(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMeSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof patchMeSettings>>>
    export type PatchMeSettingsMutationBody = UpdateSettingsRequest
    export type PatchMeSettingsMutationError = ErrorResponse

    /**
 * @summary Update operator settings
 */
export const usePatchMeSettings = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeSettings>>, TError,{data: UpdateSettingsRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchMeSettings>>,
        TError,
        {data: UpdateSettingsRequest},
        TContext
      > => {
      return useMutation(getPatchMeSettingsMutationOptions(options));
    }
    export const getGetMeThresholdsUrl = () => {




  return `/me/thresholds`
}

/**
 * Returns the current operator's alert thresholds
 * @summary Get operator thresholds
 */
export const getMeThresholds = async ( options?: Parameters<typeof customAxios>[1]): Promise<ThresholdsResult> => {

  return customAxios<ThresholdsResult>(getGetMeThresholdsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeThresholdsQueryKey = () => {
    return [
    `/me/thresholds`
    ] as const;
    }


export const getGetMeThresholdsQueryOptions = <TData = Awaited<ReturnType<typeof getMeThresholds>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeThresholds>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeThresholdsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeThresholds>>> = ({ signal }) => getMeThresholds({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMeThresholds>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeThresholdsQueryResult = NonNullable<Awaited<ReturnType<typeof getMeThresholds>>>
export type GetMeThresholdsQueryError = ErrorResponse


/**
 * @summary Get operator thresholds
 */

export function useGetMeThresholds<TData = Awaited<ReturnType<typeof getMeThresholds>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMeThresholds>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeThresholdsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchMeThresholdsUrl = () => {




  return `/me/thresholds`
}

/**
 * Updates the current operator's alert thresholds
 * @summary Update operator thresholds
 */
export const patchMeThresholds = async (thresholdUpdateRequest: ThresholdUpdateRequest, options?: Parameters<typeof customAxios>[1]): Promise<ThresholdsResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ThresholdsResult>(getPatchMeThresholdsUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(thresholdUpdateRequest)
  }
);}





export const getPatchMeThresholdsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeThresholds>>, TError,{data: ThresholdUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchMeThresholds>>, TError,{data: ThresholdUpdateRequest}, TContext> => {

const mutationKey = ['patchMeThresholds'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMeThresholds>>, {data: ThresholdUpdateRequest}> = (props) => {
          const {data} = props ?? {};

          return  patchMeThresholds(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMeThresholdsMutationResult = NonNullable<Awaited<ReturnType<typeof patchMeThresholds>>>
    export type PatchMeThresholdsMutationBody = ThresholdUpdateRequest
    export type PatchMeThresholdsMutationError = ErrorResponse

    /**
 * @summary Update operator thresholds
 */
export const usePatchMeThresholds = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMeThresholds>>, TError,{data: ThresholdUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchMeThresholds>>,
        TError,
        {data: ThresholdUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchMeThresholdsMutationOptions(options));
    }
