package storage

import (
	"strings"
	"testing"
	"time"
)

func TestNewUUIDv7(t *testing.T) {
	// Test basic generation
	uuid := NewUUIDv7()
	if len(uuid) != 36 {
		t.Errorf("UUID length = %d, want 36", len(uuid))
	}

	// Check format: xxxxxxxx-xxxx-7xxx-yxxx-xxxxxxxxxxxx
	parts := strings.Split(uuid, "-")
	if len(parts) != 5 {
		t.Fatalf("UUID has %d parts, want 5", len(parts))
	}
	if len(parts[0]) != 8 || len(parts[1]) != 4 || len(parts[2]) != 4 || len(parts[3]) != 4 || len(parts[4]) != 12 {
		t.Errorf("UUID part lengths incorrect: %v", parts)
	}

	// Check version nibble in 3rd group (index 14 in full string)
	// 3rd group is parts[2], first char must be '7'
	if parts[2][0] != '7' {
		t.Errorf("UUID version nibble = %c, want '7'", parts[2][0])
	}

	// Check variant nibble in 4th group (index 19 in full string)
	// 4th group is parts[3], first 2 bits must be '8', '9', 'a', or 'b'
	variantChar := rune(parts[3][0])
	variantChars := []rune{'8', '9', 'a', 'b', 'c', 'd', 'e'}
	isValidVariant := false
	for _, vc := range variantChars {
		if variantChar == vc {
			isValidVariant = true
			break
		}
	}
	if !isValidVariant {
		t.Errorf("UUID variant nibble = %c, want 8-9 or a-e", variantChar)
	}

	// Should be parseable
	if err := ParseUUIDv7(uuid); err != nil {
		t.Errorf("NewUUIDv7() produced unparseable UUID: %v", err)
	}
}

func TestNewUUIDv7_Uniqueness(t *testing.T) {
	// Generate multiple UUIDs and ensure uniqueness
	uuids := make(map[string]bool)
	for i := 0; i < 1000; i++ {
		uuid := NewUUIDv7()
		if uuids[uuid] {
			t.Errorf("Duplicate UUID generated: %s", uuid)
		}
		uuids[uuid] = true
	}
}

func TestNewUUIDv7_TimeOrder(t *testing.T) {
	// Generate 1000 UUIDs and verify they're all in time order
	// Since we're generating them sequentially without sleep, each should have a higher/equal timestamp
	// (or same timestamp with higher counter)
	var lastTime time.Time
	for i := 0; i < 1000; i++ {
		uuid := NewUUIDv7()
		currentTime, err := UUIDv7ToTime(uuid)
		if err != nil {
			t.Fatalf("UUIDv7ToTime(%s) failed: %v", uuid, err)
		}
		if i > 0 && currentTime.Before(lastTime) {
			t.Errorf("UUID time order incorrect at iteration %d: %v should be after %v", i, currentTime, lastTime)
		}
		lastTime = currentTime
	}
}

func TestNewUUIDv7_MonotonicWithinMillisecond(t *testing.T) {
	// Within the same millisecond, UUIDs should be monotonically increasing
	// Generate many UUIDs in quick succession
	var uuids []string
	for i := 0; i < 100; i++ {
		uuid := NewUUIDv7()
		uuids = append(uuids, uuid)
	}

	// All UUIDs should be parseable
	for _, uuid := range uuids {
		if err := ParseUUIDv7(uuid); err != nil {
			t.Errorf("UUID %s failed to parse: %v", uuid, err)
		}
	}

	// All UUIDs should be unique
	seen := make(map[string]bool)
	for _, uuid := range uuids {
		if seen[uuid] {
			t.Errorf("Duplicate UUID in sequence: %s", uuid)
		}
		seen[uuid] = true
	}
}

func TestParseUUIDv7_Valid(t *testing.T) {
	// Valid UUIDv7 generated by NewUUIDv7
	uuid := NewUUIDv7()
	if err := ParseUUIDv7(uuid); err != nil {
		t.Errorf("ParseUUIDv7(%s) failed: %v", uuid, err)
	}
}

func TestParseUUIDv7_InvalidLength(t *testing.T) {
	testCases := []struct {
		name  string
		uuid  string
		wantErr bool
	}{
		{"empty", "", true},
		{"too short", "12345678-1234-7xxx-xxxx-123456789012", true},
		{"too long", "12345678-1234-7xxx-xxxx-12345678901234", true},
		{"no hyphens", "1234567812347xxx8xxx123456789012", true},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := ParseUUIDv7(tc.uuid)
			if tc.wantErr && err == nil {
				t.Error("ParseUUIDv7() expected error, got nil")
			}
			if !tc.wantErr && err != nil {
				t.Errorf("ParseUUIDv7() unexpected error: %v", err)
			}
		})
	}
}

func TestParseUUIDv7_InvalidFormat(t *testing.T) {
	testCases := []struct {
		name string
		uuid string
	}{
		{"wrong hyphen pos 1", "1234567-8-1234-7xxx-xxxx-123456789012"},
		{"wrong hyphen pos 2", "12345678-123-4567-7xxx-xxxx-123456789012"},
		{"wrong hyphen pos 3", "12345678-1234-7x6x-xxxx-123456789012"},
		{"wrong hyphen pos 4", "12345678-1234-7xxx-x8xx-123456789012"},
		{"non-hex char in group 1", "1234567g-1234-7xxx-xxxx-123456789012"},
		{"non-hex char in group 2", "12345678-123g-7xxx-xxxx-123456789012"},
		{"non-hex char in group 3", "12345678-1234-7gxg-xxxx-123456789012"},
		{"non-hex char in group 4", "12345678-1234-7xxx-xgxx-123456789012"},
		{"non-hex char in group 5", "12345678-1234-7xxx-xxxx-12345678901g"},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			err := ParseUUIDv7(tc.uuid)
			if err == nil {
				t.Errorf("ParseUUIDv7(%s) expected error, got nil", tc.uuid)
			}
		})
	}
}

func TestParseUUIDv7_WrongVersion(t *testing.T) {
	// UUIDv7 has '7' as first char of 3rd group
	// Test with version 4 (standard random UUID)
	uuid := "12345678-1234-4123-8012-123456789012"
	err := ParseUUIDv7(uuid)
	if err == nil {
		t.Error("ParseUUIDv7() expected error for version 4, got nil")
	}
}

func TestParseUUIDv7_WrongVariant(t *testing.T) {
	// UUIDv7 variant should be 10xx (first char of 4th group should be 8-b)
	// Test with variant 0xxx (would be '0')
	uuid := "12345678-1234-7abc-0123-123456789012"
	err := ParseUUIDv7(uuid)
	if err == nil {
		t.Error("ParseUUIDv7() expected error for wrong variant, got nil")
	}

	// Test with variant 11xx (would be 'c' or higher)
	uuid = "12345678-1234-7abc-c123-123456789012"
	err = ParseUUIDv7(uuid)
	if err == nil {
		t.Error("ParseUUIDv7() expected error for variant 11xx, got nil")
	}
}

func TestIsUUIDv7(t *testing.T) {
	// Valid UUIDv7
	valid := NewUUIDv7()
	if !IsUUIDv7(valid) {
		t.Error("IsUUIDv7() returned false for valid UUID")
	}

	// Invalid UUIDs
	invalid := []string{
		"",
		"not-a-uuid",
		"12345678-1234-4abc-0123-123456789012", // version 4
		"12345678-1234-7abc-0123-123456789012", // wrong variant
	}
	for _, uuid := range invalid {
		if IsUUIDv7(uuid) {
			t.Errorf("IsUUIDv7() returned true for %q", uuid)
		}
	}
}

func TestUUIDv7ToTime(t *testing.T) {
	// Generate a UUID and verify the time extraction is reasonable
	uuid := NewUUIDv7()

	extractedTime, err := UUIDv7ToTime(uuid)
	if err != nil {
		t.Fatalf("UUIDv7ToTime(%s) failed: %v", uuid, err)
	}

	// Verify the extracted time is recent (within the last year from Go's perspective)
	// Using a very wide range since we just want to verify the function works
	oneYearAgo := time.Now().AddDate(-1, 0, 0)
	oneYearAhead := time.Now().AddDate(1, 0, 0)
	if extractedTime.Before(oneYearAgo) || extractedTime.After(oneYearAhead) {
		t.Errorf("UUIDv7ToTime() = %v, want time between %v and %v", extractedTime, oneYearAgo, oneYearAhead)
	}
}

func TestUUIDv7ToTime_RoundTrip(t *testing.T) {
	// Test that extracting time from a UUID gives consistent results
	uuid := NewUUIDv7()
	time1, err := UUIDv7ToTime(uuid)
	if err != nil {
		t.Fatalf("UUIDv7ToTime(%s) failed: %v", uuid, err)
	}

	time2, err := UUIDv7ToTime(uuid)
	if err != nil {
		t.Fatalf("UUIDv7ToTime(%s) second call failed: %v", uuid, err)
	}

	if !time1.Equal(time2) {
		t.Errorf("Round-trip time not deterministic: %v != %v", time1, time2)
	}
}

func TestUUIDv7ToTime_InvalidUUID(t *testing.T) {
	_, err := UUIDv7ToTime("invalid-uuid")
	if err == nil {
		t.Error("UUIDv7ToTime() expected error for invalid UUID, got nil")
	}

	_, err = UUIDv7ToTime("")
	if err == nil {
		t.Error("UUIDv7ToTime() expected error for empty string, got nil")
	}
}

func TestUUIDv7ToTime_ExtractsCorrectTimestamp(t *testing.T) {
	// Known UUIDv7 with known timestamp
	// The timestamp bits are in positions 0-47 (first 12 hex chars excluding hyphens)
	// For the UUID format xxxxxxxx-xxxx-7xxx-yxxx-xxxxxxxxxxxx
	// The timestamp is encoded across the first 3 groups

	// We can verify by creating a UUID and checking that the time extraction is consistent
	uuid := NewUUIDv7()
	time1, err := UUIDv7ToTime(uuid)
	if err != nil {
		t.Fatalf("UUIDv7ToTime() failed: %v", err)
	}

	// Extract time again - should be same
	time2, err := UUIDv7ToTime(uuid)
	if err != nil {
		t.Fatalf("UUIDv7ToTime() second call failed: %v", err)
	}

	if !time1.Equal(time2) {
		t.Errorf("UUIDv7ToTime() not deterministic: %v != %v", time1, time2)
	}
}

func TestIsHexChar(t *testing.T) {
	testCases := []struct {
		c    rune
		want bool
	}{
		{'0', true},
		{'9', true},
		{'a', true},
		{'f', true},
		{'A', true},
		{'F', true},
		{'g', false},
		{'z', false},
		{'G', false},
		{'Z', false},
		{'-', false},
		{' ', false},
	}

	for _, tc := range testCases {
		got := isHexChar(tc.c)
		if got != tc.want {
			t.Errorf("isHexChar(%c) = %v, want %v", tc.c, got, tc.want)
		}
	}
}

func TestHexCharToInt(t *testing.T) {
	testCases := []struct {
		c    rune
		want int
	}{
		{'0', 0},
		{'9', 9},
		{'a', 10},
		{'f', 15},
		{'A', 10},
		{'F', 15},
		{'g', 0}, // invalid char returns 0
		{'z', 0}, // invalid char returns 0
	}

	for _, tc := range testCases {
		got := hexCharToInt(tc.c)
		if got != tc.want {
			t.Errorf("hexCharToInt(%c) = %d, want %d", tc.c, got, tc.want)
		}
	}
}
