/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitVerifyRouteImport } from './routes/waitVerify'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as SettingsThresholdsRouteImport } from './routes/settings.thresholds'
import { Route as SettingsOperatorRouteImport } from './routes/settings.operator'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsConnectionRouteImport } from './routes/settings.connection'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const WaitVerifyRoute = WaitVerifyRouteImport.update({
  id: '/waitVerify',
  path: '/waitVerify',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThresholdsRoute = SettingsThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOperatorRoute = SettingsOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionRoute = SettingsConnectionRouteImport.update({
  id: '/connection',
  path: '/connection',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/alerts': typeof AlertsRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/waitVerify': typeof WaitVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/operator': typeof SettingsOperatorRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
}
export interface FileRoutesByTo {
  '/alerts': typeof AlertsRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/waitVerify': typeof WaitVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/operator': typeof SettingsOperatorRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/alerts': typeof AlertsRoute
  '/create-account': typeof CreateAccountRoute
  '/dashboard': typeof DashboardRoute
  '/device': typeof DeviceRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/updates': typeof UpdatesRoute
  '/waitVerify': typeof WaitVerifyRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/connection': typeof SettingsConnectionRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/operator': typeof SettingsOperatorRoute
  '/settings/thresholds': typeof SettingsThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/alerts'
    | '/create-account'
    | '/dashboard'
    | '/device'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/set-password'
    | '/settings'
    | '/updates'
    | '/waitVerify'
    | '/auth/callback'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/connection'
    | '/settings/notifications'
    | '/settings/operator'
    | '/settings/thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alerts'
    | '/create-account'
    | '/dashboard'
    | '/device'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/set-password'
    | '/settings'
    | '/updates'
    | '/waitVerify'
    | '/auth/callback'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/connection'
    | '/settings/notifications'
    | '/settings/operator'
    | '/settings/thresholds'
  id:
    | '__root__'
    | '/alerts'
    | '/create-account'
    | '/dashboard'
    | '/device'
    | '/diagnostics'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/set-password'
    | '/settings'
    | '/updates'
    | '/waitVerify'
    | '/auth/callback'
    | '/settings/advanced'
    | '/settings/appearance'
    | '/settings/connection'
    | '/settings/notifications'
    | '/settings/operator'
    | '/settings/thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AlertsRoute: typeof AlertsRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DashboardRoute: typeof DashboardRoute
  DeviceRoute: typeof DeviceRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UpdatesRoute: typeof UpdatesRoute
  WaitVerifyRoute: typeof WaitVerifyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitVerify': {
      id: '/waitVerify'
      path: '/waitVerify'
      fullPath: '/waitVerify'
      preLoaderRoute: typeof WaitVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/thresholds': {
      id: '/settings/thresholds'
      path: '/thresholds'
      fullPath: '/settings/thresholds'
      preLoaderRoute: typeof SettingsThresholdsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/operator': {
      id: '/settings/operator'
      path: '/operator'
      fullPath: '/settings/operator'
      preLoaderRoute: typeof SettingsOperatorRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connection': {
      id: '/settings/connection'
      path: '/connection'
      fullPath: '/settings/connection'
      preLoaderRoute: typeof SettingsConnectionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsConnectionRoute: typeof SettingsConnectionRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsOperatorRoute: typeof SettingsOperatorRoute
  SettingsThresholdsRoute: typeof SettingsThresholdsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsConnectionRoute: SettingsConnectionRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsOperatorRoute: SettingsOperatorRoute,
  SettingsThresholdsRoute: SettingsThresholdsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AlertsRoute: AlertsRoute,
  CreateAccountRoute: CreateAccountRoute,
  DashboardRoute: DashboardRoute,
  DeviceRoute: DeviceRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UpdatesRoute: UpdatesRoute,
  WaitVerifyRoute: WaitVerifyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
