/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateServiceAccountRequest,
  CreateServiceAccountTokenRequest,
  DeletedResult,
  ErrorResponse,
  RevokedResult,
  RotateServiceAccountTokenRequest,
  ServiceAccount,
  ServiceAccountListResult,
  ServiceAccountTokenCreated,
  ServiceAccountTokenListResult,
  ServiceAccountTokenRotated
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetServiceAccountsUrl = () => {




  return `/service-accounts`
}

/**
 * Returns all org-scoped service accounts
 * @summary List service accounts
 */
export const getServiceAccounts = async ( options?: Parameters<typeof customAxios>[1]): Promise<ServiceAccountListResult> => {

  return customAxios<ServiceAccountListResult>(getGetServiceAccountsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetServiceAccountsQueryKey = () => {
    return [
    `/service-accounts`
    ] as const;
    }


export const getGetServiceAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getServiceAccounts>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceAccounts>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceAccountsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceAccounts>>> = ({ signal }) => getServiceAccounts({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceAccounts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceAccounts>>>
export type GetServiceAccountsQueryError = ErrorResponse


/**
 * @summary List service accounts
 */

export function useGetServiceAccounts<TData = Awaited<ReturnType<typeof getServiceAccounts>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceAccounts>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceAccountsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostServiceAccountsUrl = () => {




  return `/service-accounts`
}

/**
 * Creates a new org-scoped service account
 * @summary Create service account
 */
export const postServiceAccounts = async (createServiceAccountRequest: CreateServiceAccountRequest, options?: Parameters<typeof customAxios>[1]): Promise<ServiceAccount> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ServiceAccount>(getPostServiceAccountsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createServiceAccountRequest)
  }
);}





export const getPostServiceAccountsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccounts>>, TError,{data: CreateServiceAccountRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceAccounts>>, TError,{data: CreateServiceAccountRequest}, TContext> => {

const mutationKey = ['postServiceAccounts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceAccounts>>, {data: CreateServiceAccountRequest}> = (props) => {
          const {data} = props ?? {};

          return  postServiceAccounts(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceAccounts>>>
    export type PostServiceAccountsMutationBody = CreateServiceAccountRequest
    export type PostServiceAccountsMutationError = ErrorResponse

    /**
 * @summary Create service account
 */
export const usePostServiceAccounts = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccounts>>, TError,{data: CreateServiceAccountRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postServiceAccounts>>,
        TError,
        {data: CreateServiceAccountRequest},
        TContext
      > => {
      return useMutation(getPostServiceAccountsMutationOptions(options));
    }
    export const getDeleteServiceAccountsIdUrl = (id: string,) => {




  return `/service-accounts/${id}`
}

/**
 * Removes a service account and its tokens
 * @summary Delete service account
 */
export const deleteServiceAccountsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<DeletedResult> => {

  return customAxios<DeletedResult>(getDeleteServiceAccountsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteServiceAccountsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteServiceAccountsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceAccountsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteServiceAccountsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceAccountsId>>>

    export type DeleteServiceAccountsIdMutationError = ErrorResponse

    /**
 * @summary Delete service account
 */
export const useDeleteServiceAccountsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceAccountsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteServiceAccountsIdMutationOptions(options));
    }
    export const getPostServiceAccountsIdRotateUrl = (id: string,) => {




  return `/service-accounts/${id}/rotate`
}

/**
 * Revokes the existing token and issues a new one. Returns the full key once
 * @summary Rotate service account token
 */
export const postServiceAccountsIdRotate = async (id: string,
    rotateServiceAccountTokenRequest: RotateServiceAccountTokenRequest, options?: Parameters<typeof customAxios>[1]): Promise<ServiceAccountTokenRotated> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ServiceAccountTokenRotated>(getPostServiceAccountsIdRotateUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(rotateServiceAccountTokenRequest)
  }
);}





export const getPostServiceAccountsIdRotateMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdRotate>>, TError,{id: string;data: RotateServiceAccountTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdRotate>>, TError,{id: string;data: RotateServiceAccountTokenRequest}, TContext> => {

const mutationKey = ['postServiceAccountsIdRotate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceAccountsIdRotate>>, {id: string;data: RotateServiceAccountTokenRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postServiceAccountsIdRotate(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceAccountsIdRotateMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceAccountsIdRotate>>>
    export type PostServiceAccountsIdRotateMutationBody = RotateServiceAccountTokenRequest
    export type PostServiceAccountsIdRotateMutationError = ErrorResponse

    /**
 * @summary Rotate service account token
 */
export const usePostServiceAccountsIdRotate = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdRotate>>, TError,{id: string;data: RotateServiceAccountTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postServiceAccountsIdRotate>>,
        TError,
        {id: string;data: RotateServiceAccountTokenRequest},
        TContext
      > => {
      return useMutation(getPostServiceAccountsIdRotateMutationOptions(options));
    }
    export const getGetServiceAccountsIdTokensUrl = (id: string,) => {




  return `/service-accounts/${id}/tokens`
}

/**
 * Returns all tokens for a service account
 * @summary List service account tokens
 */
export const getServiceAccountsIdTokens = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<ServiceAccountTokenListResult> => {

  return customAxios<ServiceAccountTokenListResult>(getGetServiceAccountsIdTokensUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetServiceAccountsIdTokensQueryKey = (id: string,) => {
    return [
    `/service-accounts/${id}/tokens`
    ] as const;
    }


export const getGetServiceAccountsIdTokensQueryOptions = <TData = Awaited<ReturnType<typeof getServiceAccountsIdTokens>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceAccountsIdTokens>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetServiceAccountsIdTokensQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getServiceAccountsIdTokens>>> = ({ signal }) => getServiceAccountsIdTokens(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getServiceAccountsIdTokens>>, TError, TData> & { queryKey: QueryKey }
}

export type GetServiceAccountsIdTokensQueryResult = NonNullable<Awaited<ReturnType<typeof getServiceAccountsIdTokens>>>
export type GetServiceAccountsIdTokensQueryError = ErrorResponse


/**
 * @summary List service account tokens
 */

export function useGetServiceAccountsIdTokens<TData = Awaited<ReturnType<typeof getServiceAccountsIdTokens>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getServiceAccountsIdTokens>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetServiceAccountsIdTokensQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostServiceAccountsIdTokensUrl = (id: string,) => {




  return `/service-accounts/${id}/tokens`
}

/**
 * Creates a new token for a service account. Returns the full key once
 * @summary Create service account token
 */
export const postServiceAccountsIdTokens = async (id: string,
    createServiceAccountTokenRequest: CreateServiceAccountTokenRequest, options?: Parameters<typeof customAxios>[1]): Promise<ServiceAccountTokenCreated> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ServiceAccountTokenCreated>(getPostServiceAccountsIdTokensUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createServiceAccountTokenRequest)
  }
);}





export const getPostServiceAccountsIdTokensMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdTokens>>, TError,{id: string;data: CreateServiceAccountTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdTokens>>, TError,{id: string;data: CreateServiceAccountTokenRequest}, TContext> => {

const mutationKey = ['postServiceAccountsIdTokens'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postServiceAccountsIdTokens>>, {id: string;data: CreateServiceAccountTokenRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  postServiceAccountsIdTokens(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostServiceAccountsIdTokensMutationResult = NonNullable<Awaited<ReturnType<typeof postServiceAccountsIdTokens>>>
    export type PostServiceAccountsIdTokensMutationBody = CreateServiceAccountTokenRequest
    export type PostServiceAccountsIdTokensMutationError = ErrorResponse

    /**
 * @summary Create service account token
 */
export const usePostServiceAccountsIdTokens = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postServiceAccountsIdTokens>>, TError,{id: string;data: CreateServiceAccountTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postServiceAccountsIdTokens>>,
        TError,
        {id: string;data: CreateServiceAccountTokenRequest},
        TContext
      > => {
      return useMutation(getPostServiceAccountsIdTokensMutationOptions(options));
    }
    export const getDeleteServiceAccountsIdTokensTokenUrl = (id: string,
    token: string,) => {




  return `/service-accounts/${id}/tokens/${token}`
}

/**
 * Revokes a single token by ID
 * @summary Revoke service account token
 */
export const deleteServiceAccountsIdTokensToken = async (id: string,
    token: string, options?: Parameters<typeof customAxios>[1]): Promise<RevokedResult> => {

  return customAxios<RevokedResult>(getDeleteServiceAccountsIdTokensTokenUrl(id,token),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteServiceAccountsIdTokensTokenMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>, TError,{id: string;token: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>, TError,{id: string;token: string}, TContext> => {

const mutationKey = ['deleteServiceAccountsIdTokensToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>, {id: string;token: string}> = (props) => {
          const {id,token} = props ?? {};

          return  deleteServiceAccountsIdTokensToken(id,token,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteServiceAccountsIdTokensTokenMutationResult = NonNullable<Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>>

    export type DeleteServiceAccountsIdTokensTokenMutationError = ErrorResponse

    /**
 * @summary Revoke service account token
 */
export const useDeleteServiceAccountsIdTokensToken = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>, TError,{id: string;token: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteServiceAccountsIdTokensToken>>,
        TError,
        {id: string;token: string},
        TContext
      > => {
      return useMutation(getDeleteServiceAccountsIdTokensTokenMutationOptions(options));
    }
