// Package swag Code generated by swaggo/swag. DO NOT EDIT
package swag

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/updates/check": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "usage-stats",
                    "usage-stats"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/alerts/rules": {
            "get": {
                "description": "Returns all org-scoped alert rules with their current instance states.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "List alert rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "alert rules with instances",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "org context missing",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new org-scoped alert rule. Validated before persistence.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Create alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "rule definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers_alert.ruleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "created rule with instances",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "invalid input",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alerts/rules/{id}": {
            "get": {
                "description": "Returns one alert rule with its current instance states.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Get alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "rule with instances",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "not found / forbidden",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes the rule and its instances.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Delete alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "deleted confirmation",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "patch": {
                "description": "Replaces a rule's mutable fields. Disabling clears its instances.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Update alert rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "rule definition",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api_handlers_alert.ruleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "updated rule with instances",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "invalid input / not found",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alerts/rules/{id}/evaluate": {
            "post": {
                "description": "Triggers evaluation on the rule's metric immediately.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Manually evaluate a rule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "evaluation result (transitioned index)",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "evaluation failed",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/alerts/rules/{id}/history": {
            "get": {
                "description": "Transition events for an org, optionally narrowed to one rule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alerts"
                ],
                "summary": "Alert history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "rule ID filter",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "integer",
                        "description": "event limit (default 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "event entries",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "internal error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/annotations": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "annotations",
                    "annotations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "annotations",
                    "annotations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/annotations/{id}": {
            "delete": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "annotations",
                    "annotations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api-keys": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api-keys/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/api-keys/{id}/rotate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api-keys"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "responses": {}
            }
        },
        "/auth/login/tokens": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "responses": {}
            }
        },
        "/auth/oauth/github": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "responses": {}
            }
        },
        "/auth/oauth/google": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "responses": {}
            }
        },
        "/commands/{imei}/execute": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "commands"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/config-versions/{resource}": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "config-versions",
                    "config-versions"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/config-versions/{resource}/{version}": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "config-versions",
                    "config-versions"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/config-versions/{resource}/{version}/restore": {
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "config-versions",
                    "config-versions"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/contact-points": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/contact-points/{id}": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/contact-points/{id}/test": {
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "contact-points",
                    "contact-points"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/dashboard/stats": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "dashboard",
                    "dashboard"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/devices/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/devices/{id}/events": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/devices/{id}/events/recent": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/devices/{id}/events/{type}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/devices/{id}/logs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/diagnostics/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "diagnostics"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/inbox/{imei}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/inbox/{imei}/requests": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/inbox/{imei}/{entryId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/inbox/{imei}/{entryId}/resend": {
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "inbox",
                    "inbox"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/organizations": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/organizations/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/organizations/{id}/members": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/organizations/{id}/members/{memberId}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/organizations/{id}/members/{memberId}/role": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "members"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service-accounts": {
            "get": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "service-accounts",
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "service-accounts",
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service-accounts/{id}": {
            "delete": {
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "service-accounts",
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service-accounts/{id}/rotate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service-accounts/{id}/tokens": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/service-accounts/{id}/tokens/{token}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/telemetry/{imei}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "telemetry"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/updates/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "updates"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/updates/versions": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "updates"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/updates/versions/{id}/changelog": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "updates"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/updates/{id}/status": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "updates"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "X-Organization-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "internal_api_handlers_alert.ruleRequest": {
            "type": "object",
            "properties": {
                "condition": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "for_seconds": {
                    "type": "integer"
                },
                "metric": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notify_interval_seconds": {
                    "type": "integer"
                },
                "on_error": {
                    "type": "string"
                },
                "on_no_data": {
                    "type": "string"
                },
                "threshold": {
                    "type": "number"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
