/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConcurrentSessionsResult,
  ErrorResponse,
  RevokeResult,
  SessionInfo,
  SessionListResult,
  SuccessResult
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetAuthSessionsUrl = () => {




  return `/auth/sessions`
}

/**
 * Returns all active sessions for the authenticated operator
 * @summary List sessions
 */
export const getAuthSessions = async ( options?: Parameters<typeof customAxios>[1]): Promise<SessionListResult> => {

  return customAxios<SessionListResult>(getGetAuthSessionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthSessionsQueryKey = () => {
    return [
    `/auth/sessions`
    ] as const;
    }


export const getGetAuthSessionsQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSessions>>> = ({ signal }) => getAuthSessions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthSessionsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSessions>>>
export type GetAuthSessionsQueryError = ErrorResponse


/**
 * @summary List sessions
 */

export function useGetAuthSessions<TData = Awaited<ReturnType<typeof getAuthSessions>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessions>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthSessionsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAuthSessionsUrl = () => {




  return `/auth/sessions`
}

/**
 * Revokes all sessions except the current one
 * @summary Revoke other sessions
 */
export const deleteAuthSessions = async ( options?: Parameters<typeof customAxios>[1]): Promise<RevokeResult> => {

  return customAxios<RevokeResult>(getDeleteAuthSessionsUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAuthSessionsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessions>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessions>>, TError,void, TContext> => {

const mutationKey = ['deleteAuthSessions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAuthSessions>>, void> = () => {


          return  deleteAuthSessions(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAuthSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAuthSessions>>>

    export type DeleteAuthSessionsMutationError = ErrorResponse

    /**
 * @summary Revoke other sessions
 */
export const useDeleteAuthSessions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessions>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAuthSessions>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteAuthSessionsMutationOptions(options));
    }
    export const getGetAuthSessionsConcurrentUrl = () => {




  return `/auth/sessions/concurrent`
}

/**
 * Returns whether the operator has concurrent active logins
 * @summary Check concurrent sessions
 */
export const getAuthSessionsConcurrent = async ( options?: Parameters<typeof customAxios>[1]): Promise<ConcurrentSessionsResult> => {

  return customAxios<ConcurrentSessionsResult>(getGetAuthSessionsConcurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthSessionsConcurrentQueryKey = () => {
    return [
    `/auth/sessions/concurrent`
    ] as const;
    }


export const getGetAuthSessionsConcurrentQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSessionsConcurrent>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsConcurrent>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionsConcurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSessionsConcurrent>>> = ({ signal }) => getAuthSessionsConcurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsConcurrent>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthSessionsConcurrentQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSessionsConcurrent>>>
export type GetAuthSessionsConcurrentQueryError = ErrorResponse


/**
 * @summary Check concurrent sessions
 */

export function useGetAuthSessionsConcurrent<TData = Awaited<ReturnType<typeof getAuthSessionsConcurrent>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsConcurrent>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthSessionsConcurrentQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthSessionsRevokeAllUrl = () => {




  return `/auth/sessions/revoke-all`
}

/**
 * Revokes all sessions including the current one and clears the session cookie
 * @summary Revoke all sessions (all devices)
 */
export const postAuthSessionsRevokeAll = async ( options?: Parameters<typeof customAxios>[1]): Promise<RevokeResult> => {

  return customAxios<RevokeResult>(getPostAuthSessionsRevokeAllUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthSessionsRevokeAllMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>, TError,void, TContext> => {

const mutationKey = ['postAuthSessionsRevokeAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>, void> = () => {


          return  postAuthSessionsRevokeAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthSessionsRevokeAllMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>>

    export type PostAuthSessionsRevokeAllMutationError = ErrorResponse

    /**
 * @summary Revoke all sessions (all devices)
 */
export const usePostAuthSessionsRevokeAll = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthSessionsRevokeAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthSessionsRevokeAllMutationOptions(options));
    }
    export const getGetAuthSessionsIdUrl = (id: string,) => {




  return `/auth/sessions/${id}`
}

/**
 * Returns a single session by ID
 * @summary Get session
 */
export const getAuthSessionsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<SessionInfo> => {

  return customAxios<SessionInfo>(getGetAuthSessionsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthSessionsIdQueryKey = (id: string,) => {
    return [
    `/auth/sessions/${id}`
    ] as const;
    }


export const getGetAuthSessionsIdQueryOptions = <TData = Awaited<ReturnType<typeof getAuthSessionsId>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthSessionsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthSessionsId>>> = ({ signal }) => getAuthSessionsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthSessionsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthSessionsId>>>
export type GetAuthSessionsIdQueryError = ErrorResponse


/**
 * @summary Get session
 */

export function useGetAuthSessionsId<TData = Awaited<ReturnType<typeof getAuthSessionsId>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthSessionsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthSessionsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteAuthSessionsIdUrl = (id: string,) => {




  return `/auth/sessions/${id}`
}

/**
 * Revokes a specific session by ID. Cannot revoke the current session
 * @summary Revoke session
 */
export const deleteAuthSessionsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

  return customAxios<SuccessResult>(getDeleteAuthSessionsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteAuthSessionsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAuthSessionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAuthSessionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAuthSessionsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAuthSessionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAuthSessionsId>>>

    export type DeleteAuthSessionsIdMutationError = ErrorResponse

    /**
 * @summary Revoke session
 */
export const useDeleteAuthSessionsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAuthSessionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteAuthSessionsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteAuthSessionsIdMutationOptions(options));
    }
