/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CancelVerificationRequest,
  EmailVerifyRequest,
  EmailVerifyResult,
  ErrorResponse,
  ForgotPasswordRequest,
  GetAuthPollVerificationParams,
  GetAuthResendVerificationParams,
  GetAuthVerifyEmailParams,
  LockoutStatusResult,
  LoginRequest,
  LoginResult,
  LoginWithTokensResult,
  LogoutRequest,
  MeResult,
  MessageResult,
  OrganizationListResult,
  PollVerificationResult,
  PostAuthOauthGithubParams,
  PostAuthOauthGoogleParams,
  RefreshTokenRequest,
  RefreshTokenResult,
  RegisterRequest,
  RegisterResult,
  ResendVerificationRequest,
  ResetPasswordRequest,
  SelectOrganizationRequest,
  SelectOrganizationResult,
  SuccessResult
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostAuthAdminLockoutUnlockOperatorIdUrl = (operatorId: string,) => {




  return `/auth/admin/lockout/unlock/${operatorId}`
}

/**
 * Clears an operator's account lockout. Requires org-scoped super_admin
 * @summary Unlock account
 */
export const postAuthAdminLockoutUnlockOperatorId = async (operatorId: string, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

  return customAxios<SuccessResult>(getPostAuthAdminLockoutUnlockOperatorIdUrl(operatorId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthAdminLockoutUnlockOperatorIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>, TError,{operatorId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>, TError,{operatorId: string}, TContext> => {

const mutationKey = ['postAuthAdminLockoutUnlockOperatorId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>, {operatorId: string}> = (props) => {
          const {operatorId} = props ?? {};

          return  postAuthAdminLockoutUnlockOperatorId(operatorId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthAdminLockoutUnlockOperatorIdMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>>

    export type PostAuthAdminLockoutUnlockOperatorIdMutationError = ErrorResponse

    /**
 * @summary Unlock account
 */
export const usePostAuthAdminLockoutUnlockOperatorId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>, TError,{operatorId: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthAdminLockoutUnlockOperatorId>>,
        TError,
        {operatorId: string},
        TContext
      > => {
      return useMutation(getPostAuthAdminLockoutUnlockOperatorIdMutationOptions(options));
    }
    export const getPostAuthCancelVerificationUrl = () => {




  return `/auth/cancel-verification`
}

/**
 * Cancels a pending email verification for an email address
 * @summary Cancel verification
 */
export const postAuthCancelVerification = async (cancelVerificationRequest: CancelVerificationRequest, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SuccessResult>(getPostAuthCancelVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cancelVerificationRequest)
  }
);}





export const getPostAuthCancelVerificationMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthCancelVerification>>, TError,{data: CancelVerificationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthCancelVerification>>, TError,{data: CancelVerificationRequest}, TContext> => {

const mutationKey = ['postAuthCancelVerification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthCancelVerification>>, {data: CancelVerificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthCancelVerification(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthCancelVerificationMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthCancelVerification>>>
    export type PostAuthCancelVerificationMutationBody = CancelVerificationRequest
    export type PostAuthCancelVerificationMutationError = ErrorResponse

    /**
 * @summary Cancel verification
 */
export const usePostAuthCancelVerification = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthCancelVerification>>, TError,{data: CancelVerificationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthCancelVerification>>,
        TError,
        {data: CancelVerificationRequest},
        TContext
      > => {
      return useMutation(getPostAuthCancelVerificationMutationOptions(options));
    }
    export const getPostAuthForgotPasswordUrl = () => {




  return `/auth/forgot-password`
}

/**
 * Sends a password reset link to the email if it exists
 * @summary Forgot password
 */
export const postAuthForgotPassword = async (forgotPasswordRequest: ForgotPasswordRequest, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MessageResult>(getPostAuthForgotPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(forgotPasswordRequest)
  }
);}





export const getPostAuthForgotPasswordMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext> => {

const mutationKey = ['postAuthForgotPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthForgotPassword>>, {data: ForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthForgotPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthForgotPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthForgotPassword>>>
    export type PostAuthForgotPasswordMutationBody = ForgotPasswordRequest
    export type PostAuthForgotPasswordMutationError = ErrorResponse

    /**
 * @summary Forgot password
 */
export const usePostAuthForgotPassword = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthForgotPassword>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthForgotPassword>>,
        TError,
        {data: ForgotPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthForgotPasswordMutationOptions(options));
    }
    export const getGetAuthLockoutStatusUrl = () => {




  return `/auth/lockout/status`
}

/**
 * Returns the current account lockout status for the authenticated operator
 * @summary Get lockout status
 */
export const getAuthLockoutStatus = async ( options?: Parameters<typeof customAxios>[1]): Promise<LockoutStatusResult> => {

  return customAxios<LockoutStatusResult>(getGetAuthLockoutStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthLockoutStatusQueryKey = () => {
    return [
    `/auth/lockout/status`
    ] as const;
    }


export const getGetAuthLockoutStatusQueryOptions = <TData = Awaited<ReturnType<typeof getAuthLockoutStatus>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLockoutStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthLockoutStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthLockoutStatus>>> = ({ signal }) => getAuthLockoutStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthLockoutStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthLockoutStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthLockoutStatus>>>
export type GetAuthLockoutStatusQueryError = ErrorResponse


/**
 * @summary Get lockout status
 */

export function useGetAuthLockoutStatus<TData = Awaited<ReturnType<typeof getAuthLockoutStatus>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthLockoutStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthLockoutStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthLoginUrl = () => {




  return `/auth/login`
}

/**
 * Authenticates an operator with email/password and starts a session
 * @summary Operator login
 */
export const postAuthLogin = async (loginRequest: LoginRequest, options?: Parameters<typeof customAxios>[1]): Promise<LoginResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<LoginResult>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
);}





export const getPostAuthLoginMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = LoginRequest
    export type PostAuthLoginMutationError = ErrorResponse

    /**
 * @summary Operator login
 */
export const usePostAuthLogin = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options));
    }
    export const getPostAuthLoginTokensUrl = () => {




  return `/auth/login/tokens`
}

/**
 * Authenticates an operator and returns access/refresh tokens instead of a cookie
 * @summary Operator login (token response)
 */
export const postAuthLoginTokens = async (loginRequest: LoginRequest, options?: Parameters<typeof customAxios>[1]): Promise<LoginWithTokensResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<LoginWithTokensResult>(getPostAuthLoginTokensUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginRequest)
  }
);}





export const getPostAuthLoginTokensMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLoginTokens>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLoginTokens>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['postAuthLoginTokens'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLoginTokens>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLoginTokens(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginTokensMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLoginTokens>>>
    export type PostAuthLoginTokensMutationBody = LoginRequest
    export type PostAuthLoginTokensMutationError = ErrorResponse

    /**
 * @summary Operator login (token response)
 */
export const usePostAuthLoginTokens = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLoginTokens>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLoginTokens>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getPostAuthLoginTokensMutationOptions(options));
    }
    export const getPostAuthLogoutUrl = () => {




  return `/auth/logout`
}

/**
 * Ends the current session and clears the session cookie
 * @summary Logout
 */
export const postAuthLogout = async (logoutRequest?: LogoutRequest, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MessageResult>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(logoutRequest)
  }
);}





export const getPostAuthLogoutMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data?: LogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data?: LogoutRequest}, TContext> => {

const mutationKey = ['postAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, {data?: LogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>
    export type PostAuthLogoutMutationBody = LogoutRequest | undefined
    export type PostAuthLogoutMutationError = ErrorResponse

    /**
 * @summary Logout
 */
export const usePostAuthLogout = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,{data?: LogoutRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        {data?: LogoutRequest},
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options));
    }
    export const getGetAuthMeUrl = () => {




  return `/auth/me`
}

/**
 * Returns the authenticated operator's profile and organization context
 * @summary Get current operator
 */
export const getAuthMe = async ( options?: Parameters<typeof customAxios>[1]): Promise<MeResult> => {

  return customAxios<MeResult>(getGetAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthMeQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }


export const getGetAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMe>>> = ({ signal }) => getAuthMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMe>>>
export type GetAuthMeQueryError = ErrorResponse


/**
 * @summary Get current operator
 */

export function useGetAuthMe<TData = Awaited<ReturnType<typeof getAuthMe>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthMe>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthOauthGithubUrl = (params?: PostAuthOauthGithubParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/oauth/github?${stringifiedParams}` : `/auth/oauth/github`
}

/**
 * Initiates GitHub OAuth flow with a 307 redirect to GitHub
 * @summary GitHub OAuth login
 */
export const postAuthOauthGithub = async (params?: PostAuthOauthGithubParams, options?: Parameters<typeof customAxios>[1]): Promise<unknown> => {

  return customAxios<unknown>(getPostAuthOauthGithubUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthOauthGithubMutationOptions = <TError = string | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGithub>>, TError,{params?: PostAuthOauthGithubParams}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGithub>>, TError,{params?: PostAuthOauthGithubParams}, TContext> => {

const mutationKey = ['postAuthOauthGithub'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthOauthGithub>>, {params?: PostAuthOauthGithubParams}> = (props) => {
          const {params} = props ?? {};

          return  postAuthOauthGithub(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthOauthGithubMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthOauthGithub>>>

    export type PostAuthOauthGithubMutationError = string | ErrorResponse

    /**
 * @summary GitHub OAuth login
 */
export const usePostAuthOauthGithub = <TError = string | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGithub>>, TError,{params?: PostAuthOauthGithubParams}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthOauthGithub>>,
        TError,
        {params?: PostAuthOauthGithubParams},
        TContext
      > => {
      return useMutation(getPostAuthOauthGithubMutationOptions(options));
    }
    export const getPostAuthOauthGoogleUrl = (params?: PostAuthOauthGoogleParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/oauth/google?${stringifiedParams}` : `/auth/oauth/google`
}

/**
 * Initiates Google OAuth flow with a 307 redirect to Google
 * @summary Google OAuth login
 */
export const postAuthOauthGoogle = async (params?: PostAuthOauthGoogleParams, options?: Parameters<typeof customAxios>[1]): Promise<unknown> => {

  return customAxios<unknown>(getPostAuthOauthGoogleUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthOauthGoogleMutationOptions = <TError = string | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGoogle>>, TError,{params?: PostAuthOauthGoogleParams}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGoogle>>, TError,{params?: PostAuthOauthGoogleParams}, TContext> => {

const mutationKey = ['postAuthOauthGoogle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthOauthGoogle>>, {params?: PostAuthOauthGoogleParams}> = (props) => {
          const {params} = props ?? {};

          return  postAuthOauthGoogle(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthOauthGoogleMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthOauthGoogle>>>

    export type PostAuthOauthGoogleMutationError = string | ErrorResponse

    /**
 * @summary Google OAuth login
 */
export const usePostAuthOauthGoogle = <TError = string | ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOauthGoogle>>, TError,{params?: PostAuthOauthGoogleParams}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthOauthGoogle>>,
        TError,
        {params?: PostAuthOauthGoogleParams},
        TContext
      > => {
      return useMutation(getPostAuthOauthGoogleMutationOptions(options));
    }
    export const getGetAuthOrganizationsUrl = () => {




  return `/auth/organizations`
}

export const getAuthOrganizations = async ( options?: Parameters<typeof customAxios>[1]): Promise<OrganizationListResult> => {

  return customAxios<OrganizationListResult>(getGetAuthOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthOrganizationsQueryKey = () => {
    return [
    `/auth/organizations`
    ] as const;
    }


export const getGetAuthOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof getAuthOrganizations>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthOrganizationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizations>>> = ({ signal }) => getAuthOrganizations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthOrganizations>>>
export type GetAuthOrganizationsQueryError = ErrorResponse



export function useGetAuthOrganizations<TData = Awaited<ReturnType<typeof getAuthOrganizations>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthOrganizationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthOrganizationsSelectUrl = () => {




  return `/auth/organizations/select`
}

/**
 * Switches the operator's active organization context
 * @summary Select organization
 */
export const postAuthOrganizationsSelect = async (selectOrganizationRequest: SelectOrganizationRequest, options?: Parameters<typeof customAxios>[1]): Promise<SelectOrganizationResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SelectOrganizationResult>(getPostAuthOrganizationsSelectUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(selectOrganizationRequest)
  }
);}





export const getPostAuthOrganizationsSelectMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOrganizationsSelect>>, TError,{data: SelectOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthOrganizationsSelect>>, TError,{data: SelectOrganizationRequest}, TContext> => {

const mutationKey = ['postAuthOrganizationsSelect'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthOrganizationsSelect>>, {data: SelectOrganizationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthOrganizationsSelect(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthOrganizationsSelectMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthOrganizationsSelect>>>
    export type PostAuthOrganizationsSelectMutationBody = SelectOrganizationRequest
    export type PostAuthOrganizationsSelectMutationError = ErrorResponse

    /**
 * @summary Select organization
 */
export const usePostAuthOrganizationsSelect = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthOrganizationsSelect>>, TError,{data: SelectOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthOrganizationsSelect>>,
        TError,
        {data: SelectOrganizationRequest},
        TContext
      > => {
      return useMutation(getPostAuthOrganizationsSelectMutationOptions(options));
    }
    export const getGetAuthPollVerificationUrl = (params: GetAuthPollVerificationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/poll-verification?${stringifiedParams}` : `/auth/poll-verification`
}

/**
 * Polls the verification status for a token
 * @summary Poll verification status
 */
export const getAuthPollVerification = async (params: GetAuthPollVerificationParams, options?: Parameters<typeof customAxios>[1]): Promise<PollVerificationResult> => {

  return customAxios<PollVerificationResult>(getGetAuthPollVerificationUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthPollVerificationQueryKey = (params?: GetAuthPollVerificationParams,) => {
    return [
    `/auth/poll-verification`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthPollVerificationQueryOptions = <TData = Awaited<ReturnType<typeof getAuthPollVerification>>, TError = ErrorResponse>(params: GetAuthPollVerificationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthPollVerification>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthPollVerificationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthPollVerification>>> = ({ signal }) => getAuthPollVerification(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthPollVerification>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthPollVerificationQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthPollVerification>>>
export type GetAuthPollVerificationQueryError = ErrorResponse


/**
 * @summary Poll verification status
 */

export function useGetAuthPollVerification<TData = Awaited<ReturnType<typeof getAuthPollVerification>>, TError = ErrorResponse>(
 params: GetAuthPollVerificationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthPollVerification>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthPollVerificationQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthRefreshUrl = () => {




  return `/auth/refresh`
}

/**
 * Exchanges a refresh token for a new access/refresh token pair
 * @summary Refresh access token
 */
export const postAuthRefresh = async (refreshTokenRequest: RefreshTokenRequest, options?: Parameters<typeof customAxios>[1]): Promise<RefreshTokenResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<RefreshTokenResult>(getPostAuthRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(refreshTokenRequest)
  }
);}





export const getPostAuthRefreshMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext> => {

const mutationKey = ['postAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRefresh>>, {data: RefreshTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRefresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRefresh>>>
    export type PostAuthRefreshMutationBody = RefreshTokenRequest
    export type PostAuthRefreshMutationError = ErrorResponse

    /**
 * @summary Refresh access token
 */
export const usePostAuthRefresh = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRefresh>>, TError,{data: RefreshTokenRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRefresh>>,
        TError,
        {data: RefreshTokenRequest},
        TContext
      > => {
      return useMutation(getPostAuthRefreshMutationOptions(options));
    }
    export const getPostAuthRegisterUrl = () => {




  return `/auth/register`
}

/**
 * Registers a new operator account and sends a verification email
 * @summary Register operator
 */
export const postAuthRegister = async (registerRequest: RegisterRequest, options?: Parameters<typeof customAxios>[1]): Promise<RegisterResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<RegisterResult>(getPostAuthRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerRequest)
  }
);}





export const getPostAuthRegisterMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: RegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = RegisterRequest
    export type PostAuthRegisterMutationError = ErrorResponse

    /**
 * @summary Register operator
 */
export const usePostAuthRegister = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: RegisterRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: RegisterRequest},
        TContext
      > => {
      return useMutation(getPostAuthRegisterMutationOptions(options));
    }
    export const getPostAuthResendPasswordResetUrl = () => {




  return `/auth/resend-password-reset`
}

/**
 * Resends a password reset link with rate limiting
 * @summary Resend password reset
 */
export const postAuthResendPasswordReset = async (forgotPasswordRequest: ForgotPasswordRequest, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SuccessResult>(getPostAuthResendPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(forgotPasswordRequest)
  }
);}





export const getPostAuthResendPasswordResetMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendPasswordReset>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResendPasswordReset>>, TError,{data: ForgotPasswordRequest}, TContext> => {

const mutationKey = ['postAuthResendPasswordReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResendPasswordReset>>, {data: ForgotPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthResendPasswordReset(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResendPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResendPasswordReset>>>
    export type PostAuthResendPasswordResetMutationBody = ForgotPasswordRequest
    export type PostAuthResendPasswordResetMutationError = ErrorResponse

    /**
 * @summary Resend password reset
 */
export const usePostAuthResendPasswordReset = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendPasswordReset>>, TError,{data: ForgotPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResendPasswordReset>>,
        TError,
        {data: ForgotPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthResendPasswordResetMutationOptions(options));
    }
    export const getGetAuthResendVerificationUrl = (params: GetAuthResendVerificationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/resend-verification?${stringifiedParams}` : `/auth/resend-verification`
}

/**
 * Resends the verification email via a query parameter (alternative to POST)
 * @summary Resend verification email (GET)
 */
export const getAuthResendVerification = async (params: GetAuthResendVerificationParams, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getGetAuthResendVerificationUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthResendVerificationQueryKey = (params?: GetAuthResendVerificationParams,) => {
    return [
    `/auth/resend-verification`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthResendVerificationQueryOptions = <TData = Awaited<ReturnType<typeof getAuthResendVerification>>, TError = ErrorResponse>(params: GetAuthResendVerificationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthResendVerification>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthResendVerificationQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthResendVerification>>> = ({ signal }) => getAuthResendVerification(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthResendVerification>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthResendVerificationQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthResendVerification>>>
export type GetAuthResendVerificationQueryError = ErrorResponse


/**
 * @summary Resend verification email (GET)
 */

export function useGetAuthResendVerification<TData = Awaited<ReturnType<typeof getAuthResendVerification>>, TError = ErrorResponse>(
 params: GetAuthResendVerificationParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthResendVerification>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthResendVerificationQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthResendVerificationUrl = () => {




  return `/auth/resend-verification`
}

/**
 * Resends the verification email to an operator
 * @summary Resend verification email
 */
export const postAuthResendVerification = async (resendVerificationRequest: ResendVerificationRequest, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MessageResult>(getPostAuthResendVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resendVerificationRequest)
  }
);}





export const getPostAuthResendVerificationMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: ResendVerificationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: ResendVerificationRequest}, TContext> => {

const mutationKey = ['postAuthResendVerification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResendVerification>>, {data: ResendVerificationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthResendVerification(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResendVerificationMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResendVerification>>>
    export type PostAuthResendVerificationMutationBody = ResendVerificationRequest
    export type PostAuthResendVerificationMutationError = ErrorResponse

    /**
 * @summary Resend verification email
 */
export const usePostAuthResendVerification = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResendVerification>>, TError,{data: ResendVerificationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResendVerification>>,
        TError,
        {data: ResendVerificationRequest},
        TContext
      > => {
      return useMutation(getPostAuthResendVerificationMutationOptions(options));
    }
    export const getPostAuthResetPasswordUrl = () => {




  return `/auth/reset-password`
}

/**
 * Resets a password using a valid reset token
 * @summary Reset password
 */
export const postAuthResetPassword = async (resetPasswordRequest: ResetPasswordRequest, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SuccessResult>(getPostAuthResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(resetPasswordRequest)
  }
);}





export const getPostAuthResetPasswordMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext> => {

const mutationKey = ['postAuthResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthResetPassword>>, {data: ResetPasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthResetPassword>>>
    export type PostAuthResetPasswordMutationBody = ResetPasswordRequest
    export type PostAuthResetPasswordMutationError = ErrorResponse

    /**
 * @summary Reset password
 */
export const usePostAuthResetPassword = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthResetPassword>>, TError,{data: ResetPasswordRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthResetPassword>>,
        TError,
        {data: ResetPasswordRequest},
        TContext
      > => {
      return useMutation(getPostAuthResetPasswordMutationOptions(options));
    }
    export const getGetAuthVerifyEmailUrl = (params: GetAuthVerifyEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/verify-email?${stringifiedParams}` : `/auth/verify-email`
}

/**
 * Verifies an operator's email via a token query parameter (alternative to POST)
 * @summary Verify email (GET)
 */
export const getAuthVerifyEmail = async (params: GetAuthVerifyEmailParams, options?: Parameters<typeof customAxios>[1]): Promise<EmailVerifyResult> => {

  return customAxios<EmailVerifyResult>(getGetAuthVerifyEmailUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthVerifyEmailQueryKey = (params?: GetAuthVerifyEmailParams,) => {
    return [
    `/auth/verify-email`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAuthVerifyEmailQueryOptions = <TData = Awaited<ReturnType<typeof getAuthVerifyEmail>>, TError = ErrorResponse>(params: GetAuthVerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthVerifyEmail>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthVerifyEmailQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthVerifyEmail>>> = ({ signal }) => getAuthVerifyEmail(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthVerifyEmail>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthVerifyEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthVerifyEmail>>>
export type GetAuthVerifyEmailQueryError = ErrorResponse


/**
 * @summary Verify email (GET)
 */

export function useGetAuthVerifyEmail<TData = Awaited<ReturnType<typeof getAuthVerifyEmail>>, TError = ErrorResponse>(
 params: GetAuthVerifyEmailParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthVerifyEmail>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthVerifyEmailQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthVerifyEmailUrl = () => {




  return `/auth/verify-email`
}

/**
 * Verifies an operator's email using a verification token
 * @summary Verify email
 */
export const postAuthVerifyEmail = async (emailVerifyRequest: EmailVerifyRequest, options?: Parameters<typeof customAxios>[1]): Promise<EmailVerifyResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<EmailVerifyResult>(getPostAuthVerifyEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(emailVerifyRequest)
  }
);}





export const getPostAuthVerifyEmailMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: EmailVerifyRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: EmailVerifyRequest}, TContext> => {

const mutationKey = ['postAuthVerifyEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthVerifyEmail>>, {data: EmailVerifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthVerifyEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthVerifyEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthVerifyEmail>>>
    export type PostAuthVerifyEmailMutationBody = EmailVerifyRequest
    export type PostAuthVerifyEmailMutationError = ErrorResponse

    /**
 * @summary Verify email
 */
export const usePostAuthVerifyEmail = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthVerifyEmail>>, TError,{data: EmailVerifyRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthVerifyEmail>>,
        TError,
        {data: EmailVerifyRequest},
        TContext
      > => {
      return useMutation(getPostAuthVerifyEmailMutationOptions(options));
    }
