/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConfigVersion,
  ConfigVersionListResult,
  ConfigVersionRestoreResult,
  ErrorResponse,
  GetConfigVersionsResourceParams
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetConfigVersionsResourceUrl = (resource: string,
    params?: GetConfigVersionsResourceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/config-versions/${resource}?${stringifiedParams}` : `/config-versions/${resource}`
}

/**
 * Returns the version history for a resource type
 * @summary List config versions
 */
export const getConfigVersionsResource = async (resource: string,
    params?: GetConfigVersionsResourceParams, options?: Parameters<typeof customAxios>[1]): Promise<ConfigVersionListResult> => {

  return customAxios<ConfigVersionListResult>(getGetConfigVersionsResourceUrl(resource,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConfigVersionsResourceQueryKey = (resource: string,
    params?: GetConfigVersionsResourceParams,) => {
    return [
    `/config-versions/${resource}`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetConfigVersionsResourceQueryOptions = <TData = Awaited<ReturnType<typeof getConfigVersionsResource>>, TError = ErrorResponse>(resource: string,
    params?: GetConfigVersionsResourceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResource>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigVersionsResourceQueryKey(resource,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigVersionsResource>>> = ({ signal }) => getConfigVersionsResource(resource,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: resource !== null && resource !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResource>>, TError, TData> & { queryKey: QueryKey }
}

export type GetConfigVersionsResourceQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigVersionsResource>>>
export type GetConfigVersionsResourceQueryError = ErrorResponse


/**
 * @summary List config versions
 */

export function useGetConfigVersionsResource<TData = Awaited<ReturnType<typeof getConfigVersionsResource>>, TError = ErrorResponse>(
 resource: string,
    params?: GetConfigVersionsResourceParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResource>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetConfigVersionsResourceQueryOptions(resource,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetConfigVersionsResourceVersionUrl = (resource: string,
    version: number,) => {




  return `/config-versions/${resource}/${version}`
}

/**
 * Returns one config version snapshot by resource type and version number
 * @summary Get config version
 */
export const getConfigVersionsResourceVersion = async (resource: string,
    version: number, options?: Parameters<typeof customAxios>[1]): Promise<ConfigVersion> => {

  return customAxios<ConfigVersion>(getGetConfigVersionsResourceVersionUrl(resource,version),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetConfigVersionsResourceVersionQueryKey = (resource: string,
    version: number,) => {
    return [
    `/config-versions/${resource}/${version}`
    ] as const;
    }


export const getGetConfigVersionsResourceVersionQueryOptions = <TData = Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>, TError = ErrorResponse>(resource: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigVersionsResourceVersionQueryKey(resource,version);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>> = ({ signal }) => getConfigVersionsResourceVersion(resource,version, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: resource !== null && resource !== undefined && version !== null && version !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>, TError, TData> & { queryKey: QueryKey }
}

export type GetConfigVersionsResourceVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>>
export type GetConfigVersionsResourceVersionQueryError = ErrorResponse


/**
 * @summary Get config version
 */

export function useGetConfigVersionsResourceVersion<TData = Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>, TError = ErrorResponse>(
 resource: string,
    version: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getConfigVersionsResourceVersion>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetConfigVersionsResourceVersionQueryOptions(resource,version,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostConfigVersionsResourceVersionRestoreUrl = (resource: string,
    version: number,) => {




  return `/config-versions/${resource}/${version}/restore`
}

/**
 * Re-applies the version's snapshot as the live settings
 * @summary Restore config version
 */
export const postConfigVersionsResourceVersionRestore = async (resource: string,
    version: number, options?: Parameters<typeof customAxios>[1]): Promise<ConfigVersionRestoreResult> => {

  return customAxios<ConfigVersionRestoreResult>(getPostConfigVersionsResourceVersionRestoreUrl(resource,version),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostConfigVersionsResourceVersionRestoreMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>, TError,{resource: string;version: number}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>, TError,{resource: string;version: number}, TContext> => {

const mutationKey = ['postConfigVersionsResourceVersionRestore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>, {resource: string;version: number}> = (props) => {
          const {resource,version} = props ?? {};

          return  postConfigVersionsResourceVersionRestore(resource,version,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostConfigVersionsResourceVersionRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>>

    export type PostConfigVersionsResourceVersionRestoreMutationError = ErrorResponse

    /**
 * @summary Restore config version
 */
export const usePostConfigVersionsResourceVersionRestore = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>, TError,{resource: string;version: number}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postConfigVersionsResourceVersionRestore>>,
        TError,
        {resource: string;version: number},
        TContext
      > => {
      return useMutation(getPostConfigVersionsResourceVersionRestoreMutationOptions(options));
    }
