/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOrganizationRequest,
  ErrorResponse,
  MessageResult,
  Organization,
  OrganizationListResult,
  OrganizationSettingsResult,
  ThresholdUpdateRequest,
  ThresholdsResult,
  UpdateOrganizationRequest,
  UpdateOrganizationSettingsRequest
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetOrganizationsUrl = () => {




  return `/organizations`
}

/**
 * Returns all organizations the operator is a member of
 * @summary List organizations
 */
export const getOrganizations = async ( options?: Parameters<typeof customAxios>[1]): Promise<OrganizationListResult> => {

  return customAxios<OrganizationListResult>(getGetOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsQueryKey = () => {
    return [
    `/organizations`
    ] as const;
    }


export const getGetOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizations>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizations>>> = ({ signal }) => getOrganizations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizations>>>
export type GetOrganizationsQueryError = ErrorResponse


/**
 * @summary List organizations
 */

export function useGetOrganizations<TData = Awaited<ReturnType<typeof getOrganizations>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizations>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostOrganizationsUrl = () => {




  return `/organizations`
}

/**
 * Creates a new organization and makes the caller its owner
 * @summary Create organization
 */
export const postOrganizations = async (createOrganizationRequest: CreateOrganizationRequest, options?: Parameters<typeof customAxios>[1]): Promise<Organization> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<Organization>(getPostOrganizationsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createOrganizationRequest)
  }
);}





export const getPostOrganizationsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizations>>, TError,{data: CreateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrganizations>>, TError,{data: CreateOrganizationRequest}, TContext> => {

const mutationKey = ['postOrganizations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganizations>>, {data: CreateOrganizationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postOrganizations(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostOrganizationsMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganizations>>>
    export type PostOrganizationsMutationBody = CreateOrganizationRequest
    export type PostOrganizationsMutationError = ErrorResponse

    /**
 * @summary Create organization
 */
export const usePostOrganizations = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizations>>, TError,{data: CreateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postOrganizations>>,
        TError,
        {data: CreateOrganizationRequest},
        TContext
      > => {
      return useMutation(getPostOrganizationsMutationOptions(options));
    }
    export const getGetOrganizationsIdUrl = (id: string,) => {




  return `/organizations/${id}`
}

/**
 * Returns one organization by ID with member count
 * @summary Get organization
 */
export const getOrganizationsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<Organization> => {

  return customAxios<Organization>(getGetOrganizationsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsIdQueryKey = (id: string,) => {
    return [
    `/organizations/${id}`
    ] as const;
    }


export const getGetOrganizationsIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsId>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsId>>> = ({ signal }) => getOrganizationsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsId>>>
export type GetOrganizationsIdQueryError = ErrorResponse


/**
 * @summary Get organization
 */

export function useGetOrganizationsId<TData = Awaited<ReturnType<typeof getOrganizationsId>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsId>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getDeleteOrganizationsIdUrl = (id: string,) => {




  return `/organizations/${id}`
}

/**
 * Deletes an organization. Only super_admin members can delete
 * @summary Delete organization
 */
export const deleteOrganizationsId = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<MessageResult> => {

  return customAxios<MessageResult>(getDeleteOrganizationsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteOrganizationsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteOrganizationsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganizationsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteOrganizationsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrganizationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganizationsId>>>

    export type DeleteOrganizationsIdMutationError = ErrorResponse

    /**
 * @summary Delete organization
 */
export const useDeleteOrganizationsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrganizationsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteOrganizationsIdMutationOptions(options));
    }
    export const getPatchOrganizationsIdUrl = (id: string,) => {




  return `/organizations/${id}`
}

/**
 * Updates mutable organization fields. Sensitive fields (maxMembers, isActive) require super_admin
 * @summary Update organization
 */
export const patchOrganizationsId = async (id: string,
    updateOrganizationRequest: UpdateOrganizationRequest, options?: Parameters<typeof customAxios>[1]): Promise<Organization> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<Organization>(getPatchOrganizationsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateOrganizationRequest)
  }
);}





export const getPatchOrganizationsIdMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsId>>, TError,{id: string;data: UpdateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsId>>, TError,{id: string;data: UpdateOrganizationRequest}, TContext> => {

const mutationKey = ['patchOrganizationsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrganizationsId>>, {id: string;data: UpdateOrganizationRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchOrganizationsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchOrganizationsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrganizationsId>>>
    export type PatchOrganizationsIdMutationBody = UpdateOrganizationRequest
    export type PatchOrganizationsIdMutationError = ErrorResponse

    /**
 * @summary Update organization
 */
export const usePatchOrganizationsId = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsId>>, TError,{id: string;data: UpdateOrganizationRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchOrganizationsId>>,
        TError,
        {id: string;data: UpdateOrganizationRequest},
        TContext
      > => {
      return useMutation(getPatchOrganizationsIdMutationOptions(options));
    }
    export const getGetOrganizationsIdSettingsUrl = (id: string,) => {




  return `/organizations/${id}/settings`
}

/**
 * Returns organization-level settings
 * @summary Get organization settings
 */
export const getOrganizationsIdSettings = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<OrganizationSettingsResult> => {

  return customAxios<OrganizationSettingsResult>(getGetOrganizationsIdSettingsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsIdSettingsQueryKey = (id: string,) => {
    return [
    `/organizations/${id}/settings`
    ] as const;
    }


export const getGetOrganizationsIdSettingsQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsIdSettings>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettings>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsIdSettingsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsIdSettings>>> = ({ signal }) => getOrganizationsIdSettings(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettings>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsIdSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsIdSettings>>>
export type GetOrganizationsIdSettingsQueryError = ErrorResponse


/**
 * @summary Get organization settings
 */

export function useGetOrganizationsIdSettings<TData = Awaited<ReturnType<typeof getOrganizationsIdSettings>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettings>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsIdSettingsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchOrganizationsIdSettingsUrl = (id: string,) => {




  return `/organizations/${id}/settings`
}

/**
 * Updates organization-level settings
 * @summary Update organization settings
 */
export const patchOrganizationsIdSettings = async (id: string,
    updateOrganizationSettingsRequest: UpdateOrganizationSettingsRequest, options?: Parameters<typeof customAxios>[1]): Promise<OrganizationSettingsResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<OrganizationSettingsResult>(getPatchOrganizationsIdSettingsUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateOrganizationSettingsRequest)
  }
);}





export const getPatchOrganizationsIdSettingsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettings>>, TError,{id: string;data: UpdateOrganizationSettingsRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettings>>, TError,{id: string;data: UpdateOrganizationSettingsRequest}, TContext> => {

const mutationKey = ['patchOrganizationsIdSettings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrganizationsIdSettings>>, {id: string;data: UpdateOrganizationSettingsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchOrganizationsIdSettings(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchOrganizationsIdSettingsMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrganizationsIdSettings>>>
    export type PatchOrganizationsIdSettingsMutationBody = UpdateOrganizationSettingsRequest
    export type PatchOrganizationsIdSettingsMutationError = ErrorResponse

    /**
 * @summary Update organization settings
 */
export const usePatchOrganizationsIdSettings = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettings>>, TError,{id: string;data: UpdateOrganizationSettingsRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchOrganizationsIdSettings>>,
        TError,
        {id: string;data: UpdateOrganizationSettingsRequest},
        TContext
      > => {
      return useMutation(getPatchOrganizationsIdSettingsMutationOptions(options));
    }
    export const getGetOrganizationsIdSettingsThresholdsUrl = (id: string,) => {




  return `/organizations/${id}/settings/thresholds`
}

/**
 * Returns organization-level alert thresholds
 * @summary Get organization thresholds
 */
export const getOrganizationsIdSettingsThresholds = async (id: string, options?: Parameters<typeof customAxios>[1]): Promise<ThresholdsResult> => {

  return customAxios<ThresholdsResult>(getGetOrganizationsIdSettingsThresholdsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetOrganizationsIdSettingsThresholdsQueryKey = (id: string,) => {
    return [
    `/organizations/${id}/settings/thresholds`
    ] as const;
    }


export const getGetOrganizationsIdSettingsThresholdsQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>, TError = ErrorResponse>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationsIdSettingsThresholdsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>> = ({ signal }) => getOrganizationsIdSettingsThresholds(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>, TError, TData> & { queryKey: QueryKey }
}

export type GetOrganizationsIdSettingsThresholdsQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>>
export type GetOrganizationsIdSettingsThresholdsQueryError = ErrorResponse


/**
 * @summary Get organization thresholds
 */

export function useGetOrganizationsIdSettingsThresholds<TData = Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>, TError = ErrorResponse>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsIdSettingsThresholds>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetOrganizationsIdSettingsThresholdsQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPatchOrganizationsIdSettingsThresholdsUrl = (id: string,) => {




  return `/organizations/${id}/settings/thresholds`
}

/**
 * Updates organization-level alert thresholds
 * @summary Update organization thresholds
 */
export const patchOrganizationsIdSettingsThresholds = async (id: string,
    thresholdUpdateRequest: ThresholdUpdateRequest, options?: Parameters<typeof customAxios>[1]): Promise<ThresholdsResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ThresholdsResult>(getPatchOrganizationsIdSettingsThresholdsUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(thresholdUpdateRequest)
  }
);}





export const getPatchOrganizationsIdSettingsThresholdsMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>, TError,{id: string;data: ThresholdUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>, TError,{id: string;data: ThresholdUpdateRequest}, TContext> => {

const mutationKey = ['patchOrganizationsIdSettingsThresholds'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>, {id: string;data: ThresholdUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  patchOrganizationsIdSettingsThresholds(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchOrganizationsIdSettingsThresholdsMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>>
    export type PatchOrganizationsIdSettingsThresholdsMutationBody = ThresholdUpdateRequest
    export type PatchOrganizationsIdSettingsThresholdsMutationError = ErrorResponse

    /**
 * @summary Update organization thresholds
 */
export const usePatchOrganizationsIdSettingsThresholds = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>, TError,{id: string;data: ThresholdUpdateRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof patchOrganizationsIdSettingsThresholds>>,
        TError,
        {id: string;data: ThresholdUpdateRequest},
        TContext
      > => {
      return useMutation(getPatchOrganizationsIdSettingsThresholdsMutationOptions(options));
    }
