/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  MFABackupCodeRequest,
  MFABackupCodeResult,
  MFADisableRequest,
  MFAEnableRequest,
  MFAEnableResult,
  MFAEnrollResult,
  MFARegenerateResult,
  MFAStatusResult,
  MFAVerifyRequest,
  MFAVerifyResult,
  MFAVerifySetupRequest,
  SuccessResult
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostAuthMfaDisableUrl = () => {




  return `/auth/mfa/disable`
}

/**
 * Disables MFA after verifying a TOTP code
 * @summary Disable MFA
 */
export const postAuthMfaDisable = async (mFADisableRequest: MFADisableRequest, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SuccessResult>(getPostAuthMfaDisableUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(mFADisableRequest)
  }
);}





export const getPostAuthMfaDisableMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaDisable>>, TError,{data: MFADisableRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaDisable>>, TError,{data: MFADisableRequest}, TContext> => {

const mutationKey = ['postAuthMfaDisable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaDisable>>, {data: MFADisableRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthMfaDisable(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaDisableMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaDisable>>>
    export type PostAuthMfaDisableMutationBody = MFADisableRequest
    export type PostAuthMfaDisableMutationError = ErrorResponse

    /**
 * @summary Disable MFA
 */
export const usePostAuthMfaDisable = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaDisable>>, TError,{data: MFADisableRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaDisable>>,
        TError,
        {data: MFADisableRequest},
        TContext
      > => {
      return useMutation(getPostAuthMfaDisableMutationOptions(options));
    }
    export const getPostAuthMfaEnableUrl = () => {




  return `/auth/mfa/enable`
}

/**
 * Enables MFA after verifying a TOTP code and returns backup codes
 * @summary Enable MFA
 */
export const postAuthMfaEnable = async (mFAEnableRequest: MFAEnableRequest, options?: Parameters<typeof customAxios>[1]): Promise<MFAEnableResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MFAEnableResult>(getPostAuthMfaEnableUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(mFAEnableRequest)
  }
);}





export const getPostAuthMfaEnableMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnable>>, TError,{data: MFAEnableRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnable>>, TError,{data: MFAEnableRequest}, TContext> => {

const mutationKey = ['postAuthMfaEnable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaEnable>>, {data: MFAEnableRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthMfaEnable(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaEnableMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaEnable>>>
    export type PostAuthMfaEnableMutationBody = MFAEnableRequest
    export type PostAuthMfaEnableMutationError = ErrorResponse

    /**
 * @summary Enable MFA
 */
export const usePostAuthMfaEnable = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnable>>, TError,{data: MFAEnableRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaEnable>>,
        TError,
        {data: MFAEnableRequest},
        TContext
      > => {
      return useMutation(getPostAuthMfaEnableMutationOptions(options));
    }
    export const getPostAuthMfaEnrollUrl = () => {




  return `/auth/mfa/enroll`
}

/**
 * Generates a new TOTP MFA secret and enrollment URI
 * @summary Enroll MFA
 */
export const postAuthMfaEnroll = async ( options?: Parameters<typeof customAxios>[1]): Promise<MFAEnrollResult> => {

  return customAxios<MFAEnrollResult>(getPostAuthMfaEnrollUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthMfaEnrollMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnroll>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnroll>>, TError,void, TContext> => {

const mutationKey = ['postAuthMfaEnroll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaEnroll>>, void> = () => {


          return  postAuthMfaEnroll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaEnrollMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaEnroll>>>

    export type PostAuthMfaEnrollMutationError = ErrorResponse

    /**
 * @summary Enroll MFA
 */
export const usePostAuthMfaEnroll = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaEnroll>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaEnroll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthMfaEnrollMutationOptions(options));
    }
    export const getPostAuthMfaRegenerateBackupCodesUrl = () => {




  return `/auth/mfa/regenerate-backup-codes`
}

/**
 * Generates and persists a new set of MFA backup codes
 * @summary Regenerate MFA backup codes
 */
export const postAuthMfaRegenerateBackupCodes = async ( options?: Parameters<typeof customAxios>[1]): Promise<MFARegenerateResult> => {

  return customAxios<MFARegenerateResult>(getPostAuthMfaRegenerateBackupCodesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthMfaRegenerateBackupCodesMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>, TError,void, TContext> => {

const mutationKey = ['postAuthMfaRegenerateBackupCodes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>, void> = () => {


          return  postAuthMfaRegenerateBackupCodes(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaRegenerateBackupCodesMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>>

    export type PostAuthMfaRegenerateBackupCodesMutationError = ErrorResponse

    /**
 * @summary Regenerate MFA backup codes
 */
export const usePostAuthMfaRegenerateBackupCodes = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>, TError,void, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaRegenerateBackupCodes>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthMfaRegenerateBackupCodesMutationOptions(options));
    }
    export const getGetAuthMfaStatusUrl = () => {




  return `/auth/mfa/status`
}

/**
 * Returns whether MFA is enabled for the current operator
 * @summary Get MFA status
 */
export const getAuthMfaStatus = async ( options?: Parameters<typeof customAxios>[1]): Promise<MFAStatusResult> => {

  return customAxios<MFAStatusResult>(getGetAuthMfaStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAuthMfaStatusQueryKey = () => {
    return [
    `/auth/mfa/status`
    ] as const;
    }


export const getGetAuthMfaStatusQueryOptions = <TData = Awaited<ReturnType<typeof getAuthMfaStatus>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthMfaStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAuthMfaStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthMfaStatus>>> = ({ signal }) => getAuthMfaStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAuthMfaStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAuthMfaStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthMfaStatus>>>
export type GetAuthMfaStatusQueryError = ErrorResponse


/**
 * @summary Get MFA status
 */

export function useGetAuthMfaStatus<TData = Awaited<ReturnType<typeof getAuthMfaStatus>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAuthMfaStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAuthMfaStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostAuthMfaVerifyUrl = () => {




  return `/auth/mfa/verify`
}

/**
 * Completes login by verifying an MFA code and creating a session with tokens
 * @summary Verify MFA (login)
 */
export const postAuthMfaVerify = async (mFAVerifyRequest: MFAVerifyRequest, options?: Parameters<typeof customAxios>[1]): Promise<MFAVerifyResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MFAVerifyResult>(getPostAuthMfaVerifyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(mFAVerifyRequest)
  }
);}





export const getPostAuthMfaVerifyMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerify>>, TError,{data: MFAVerifyRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerify>>, TError,{data: MFAVerifyRequest}, TContext> => {

const mutationKey = ['postAuthMfaVerify'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaVerify>>, {data: MFAVerifyRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthMfaVerify(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaVerify>>>
    export type PostAuthMfaVerifyMutationBody = MFAVerifyRequest
    export type PostAuthMfaVerifyMutationError = ErrorResponse

    /**
 * @summary Verify MFA (login)
 */
export const usePostAuthMfaVerify = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerify>>, TError,{data: MFAVerifyRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaVerify>>,
        TError,
        {data: MFAVerifyRequest},
        TContext
      > => {
      return useMutation(getPostAuthMfaVerifyMutationOptions(options));
    }
    export const getPostAuthMfaVerifyBackupUrl = () => {




  return `/auth/mfa/verify-backup`
}

/**
 * Verifies a backup code for an operator with MFA enabled
 * @summary Verify MFA backup code
 */
export const postAuthMfaVerifyBackup = async (mFABackupCodeRequest: MFABackupCodeRequest, options?: Parameters<typeof customAxios>[1]): Promise<MFABackupCodeResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<MFABackupCodeResult>(getPostAuthMfaVerifyBackupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(mFABackupCodeRequest)
  }
);}





export const getPostAuthMfaVerifyBackupMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>, TError,{data: MFABackupCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>, TError,{data: MFABackupCodeRequest}, TContext> => {

const mutationKey = ['postAuthMfaVerifyBackup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>, {data: MFABackupCodeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthMfaVerifyBackup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaVerifyBackupMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>>
    export type PostAuthMfaVerifyBackupMutationBody = MFABackupCodeRequest
    export type PostAuthMfaVerifyBackupMutationError = ErrorResponse

    /**
 * @summary Verify MFA backup code
 */
export const usePostAuthMfaVerifyBackup = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>, TError,{data: MFABackupCodeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaVerifyBackup>>,
        TError,
        {data: MFABackupCodeRequest},
        TContext
      > => {
      return useMutation(getPostAuthMfaVerifyBackupMutationOptions(options));
    }
    export const getPostAuthMfaVerifySetupUrl = () => {




  return `/auth/mfa/verify-setup`
}

/**
 * Verifies a TOTP code during MFA enrollment setup
 * @summary Verify MFA setup
 */
export const postAuthMfaVerifySetup = async (mFAVerifySetupRequest: MFAVerifySetupRequest, options?: Parameters<typeof customAxios>[1]): Promise<SuccessResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<SuccessResult>(getPostAuthMfaVerifySetupUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(mFAVerifySetupRequest)
  }
);}





export const getPostAuthMfaVerifySetupMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifySetup>>, TError,{data: MFAVerifySetupRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifySetup>>, TError,{data: MFAVerifySetupRequest}, TContext> => {

const mutationKey = ['postAuthMfaVerifySetup'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthMfaVerifySetup>>, {data: MFAVerifySetupRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthMfaVerifySetup(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthMfaVerifySetupMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthMfaVerifySetup>>>
    export type PostAuthMfaVerifySetupMutationBody = MFAVerifySetupRequest
    export type PostAuthMfaVerifySetupMutationError = ErrorResponse

    /**
 * @summary Verify MFA setup
 */
export const usePostAuthMfaVerifySetup = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthMfaVerifySetup>>, TError,{data: MFAVerifySetupRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthMfaVerifySetup>>,
        TError,
        {data: MFAVerifySetupRequest},
        TContext
      > => {
      return useMutation(getPostAuthMfaVerifySetupMutationOptions(options));
    }
