#!/usr/bin/env python3
"""Generate Zod schemas from the OpenAPI 3.0 spec (openapi3.json).

Reads the same spec that orval consumes (apps/api/swag/openapi3.json) and
emits Zod validation schemas alongside the generated TypeScript types. The
generated Zod covers structural validation (types, arrays, refs, maps).
Business rules (cross-field, semantic) are hand-added as .refine() calls in
the domain modules that import these schemas.

Output: packages/API_Client/src/generated/vyzorixUpdateServerAPI.zod.ts
"""
import json
import re

SPEC_PATH = "apps/api/swag/openapi3.json"
OUT_PATH = "packages/API_Client/src/generated/vyzorixUpdateServerAPI.zod.ts"

d = json.load(open(SPEC_PATH))
schemas = d.get("components", {}).get("schemas", {})

# Zod name = schema name (PascalCase, matches the orval TypeScript type name).
# Property names are kept as-is (matching the server's json tags).


def ref_name(ref):
    """Extract the schema name from a $ref string."""
    return ref.split("/")[-1]


def is_optional(prop, required_list):
    """A property is optional if it's not in the required list."""
    return prop not in (required_list or [])


def convert_type(prop_schema, indent=2):
    """Convert an OpenAPI schema fragment to a Zod expression string."""
    if not isinstance(prop_schema, dict):
        return "z.unknown()"

    # $ref → lazy reference to avoid circular init issues
    if "$ref" in prop_schema:
        name = ref_name(prop_schema["$ref"])
        return f"z.lazy(() => {name}Schema)"

    t = prop_schema.get("type")

    # Handle enum
    if "enum" in prop_schema:
        vals = ", ".join(f'"{v}"' for v in prop_schema["enum"])
        return f"z.enum([{vals}])"

    if t == "string":
        return "z.string()"

    if t == "integer":
        return "z.number().int()"

    if t == "number":
        return "z.number()"

    if t == "boolean":
        return "z.boolean()"

    if t == "array":
        items = convert_type(prop_schema.get("items", {}), indent)
        return f"z.array({items})"

    if t == "object":
        # Object with additionalProperties → Zod record
        if "additionalProperties" in prop_schema and not prop_schema.get("properties"):
            ap = prop_schema["additionalProperties"]
            if isinstance(ap, dict):
                val_type = convert_type(ap, indent)
                return f"z.record(z.string(), {val_type})"
            return "z.record(z.string(), z.unknown())"

        # Object with properties → inline object schema
        if "properties" in prop_schema:
            return convert_object(prop_schema, indent)

        # Freeform object
        return "z.record(z.string(), z.unknown())"

    # Binary (file downloads)
    if prop_schema.get("format") == "binary":
        return "z.unknown()"

    return "z.unknown()"


def make_optional(expr, optional):
    """Wrap a Zod expression in .optional() if the property is optional."""
    if optional:
        return f"{expr}.optional()"
    return expr


def convert_object(schema, indent=2):
    """Convert an object schema to a z.object() expression."""
    props = schema.get("properties", {})
    required = schema.get("required", [])

    if not props:
        # Check additionalProperties
        if "additionalProperties" in schema:
            ap = schema["additionalProperties"]
            if isinstance(ap, dict):
                val_type = convert_type(ap, indent)
                return f"z.record(z.string(), {val_type})"
        return "z.record(z.string(), z.unknown())"

    pad = "  " * indent
    inner_pad = "  " * (indent + 1)
    lines = []
    for pname, pschema in props.items():
        optional = is_optional(pname, required)
        expr = convert_type(pschema, indent + 1)
        expr = make_optional(expr, optional)
        # Use quoted key if it contains non-alphanumeric chars
        if re.match(r'^[a-zA-Z_$][a-zA-Z0-9_$]*$', pname):
            lines.append(f"{inner_pad}{pname}: {expr},")
        else:
            lines.append(f'{inner_pad}"{pname}": {expr},')

    if not lines:
        return "z.record(z.string(), z.unknown())"

    body = "\n".join(lines)
    return f"z.object({{\n{body}\n{pad}}})"


# Generate the output file
header = """// Code generated by tooling/codegen/build_zod.py from apps/api/swag/openapi3.json.
// DO NOT EDIT MANUALLY — regenerate with: python3 tooling/codegen/build_zod.py
//
// Structural Zod schemas mirroring the OpenAPI 3.0 components.schemas.
// Business-rule validation (.refine for cross-field, semantic rules) belongs
// in the domain modules that import these schemas, not here.
import { z } from 'zod';

"""

schema_lines = []

# Sort schemas for deterministic output (dependencies before dependents where
# possible; z.lazy handles circular refs so order doesn't break correctness).
for name in sorted(schemas.keys()):
    schema = schemas[name]
    expr = convert_object(schema, indent=0)

    # Flatten single-line z.object for readability
    if "\n" not in expr and len(expr) < 80:
        schema_lines.append(f"export const {name}Schema = {expr};\n")
    else:
        schema_lines.append(f"export const {name}Schema = {expr};\n")

with open(OUT_PATH, "w") as f:
    f.write(header)
    for line in schema_lines:
        f.write(line)
    f.write("\n")

print(f"zod: {len(schemas)} schemas → {OUT_PATH}")
