#!/usr/bin/env python3
"""Post-process orval react-query output: rename generic tag files to
explicit Vyzorix-domain filenames.

orval generates files as <tag>/<tag>.ts (e.g., devices/devices.ts).
This script renames them to explicit names (e.g., device-management.ts)
and fixes the rest-bridge import path.

Run after: node node_modules/.pnpm/orval*/node_modules/orval/dist/bin/orval.mjs --config orval.config.js
"""
import json
import os
import shutil

SOURCE = "apps/VyzoriX_web/src/generated-rq"
DEST = SOURCE  # orval now outputs directly to the web app; we rename in-place

# Map: orval tag name → explicit Vyzorix filename (without .ts)
# This gives every file a name that's self-explanatory without context.
TAG_RENAMES = {
    "admin": "admin-operations",
    "alerts": "alert-rules",
    "annotations": "dashboard-annotations",
    "api-keys": "operator-api-keys",
    "auth": "auth-session",
    "channels": "websocket-channels",
    "client-credentials": "oauth-client-credentials",
    "commands": "device-commands",
    "config-versions": "config-version-history",
    "connections": "device-connections",
    "contact-points": "notification-contact-points",
    "dashboard": "dashboard-stats",
    "devices": "device-management",
    "diagnostics": "device-diagnostics",
    "inbox": "device-inbox",
    "invitations": "organization-invitations",
    "members": "organization-members",
    "mfa": "mfa-management",
    "organizations": "organization-management",
    "service-accounts": "service-accounts-management",
    "sessions": "auth-sessions",
    "settings": "operator-settings",
    "telemetry": "device-telemetry",
    "updater": "ota-updater",
    "updates": "update-management",
    "usage-stats": "usage-statistics",
}

def main():
    if not os.path.isdir(SOURCE):
        print(f"Source not found: {SOURCE}")
        return

    # The schemas file stays at the root level — don't touch it.
    schemas_src = os.path.join(SOURCE, "vyzorixUpdateServerAPI.schemas.ts")
    schemas_content = None
    if os.path.exists(schemas_src):
        with open(schemas_src) as f:
            schemas_content = f.read()

    # Collect all tag directories before renaming (can't rename while iterating)
    tag_dirs = []
    for name in sorted(os.listdir(SOURCE)):
        full = os.path.join(SOURCE, name)
        if os.path.isdir(full):
            tag_dirs.append((name, full))

    index_lines = []

    for tag_name, tag_dir in tag_dirs:
        # Find the .ts file inside
        ts_files = [f for f in os.listdir(tag_dir) if f.endswith(".ts")]
        if not ts_files:
            continue

        old_filename = ts_files[0]
        old_basename = old_filename.replace(".ts", "")
        new_basename = TAG_RENAMES.get(tag_name, tag_name)
        new_dir = os.path.join(SOURCE, tag_name)  # keep original folder name

        # Read old file
        old_path = os.path.join(tag_dir, old_filename)
        with open(old_path) as f:
            content = f.read()

        # Fix rest-bridge import path
        content = content.replace(
            "../../generated/rest-bridge",
            "../../../../packages/API_Client/src/generated/rest-bridge",
        )

        # Fix schemas import: point directly to @vyzorix/api-client instead
        # of the local duplicate vyzorixUpdateServerAPI.schemas.ts
        content = content.replace(
            "from '../vyzorixUpdateServerAPI.schemas'",
            "from '@vyzorix/api-client'",
        )

        # Create new dir and write file
        os.makedirs(new_dir, exist_ok=True)
        new_path = os.path.join(new_dir, f"{new_basename}.ts")
        with open(new_path, "w") as f:
            f.write(content)

        # Copy any additional files from old dir
        for item in os.listdir(tag_dir):
            if item.endswith(".ts") and item != old_filename:
                src = os.path.join(tag_dir, item)
                dst = os.path.join(new_dir, item)
                if not os.path.exists(dst):
                    shutil.copy2(src, dst)

        # Remove old file (folder stays, we write new file into it)
        if old_filename != f"{new_basename}.ts":
            os.remove(old_path)

        index_lines.append(f'export * from "./{tag_name}/{new_basename}";')
        print(f"  {tag_name}/{old_filename} → {tag_name}/{new_basename}.ts")

    # Write index.ts barrel
    index_path = os.path.join(SOURCE, "index.ts")
    with open(index_path, "w") as f:
        f.write("// Generated by orval + tooling/codegen/organize_query_hooks.py\n")
        f.write("// DO NOT EDIT MANUALLY — regenerate with:\n")
        f.write("//   node node_modules/.pnpm/orval*/node_modules/orval/dist/bin/orval.mjs --config orval.config.js\n")
        f.write("//   python3 tooling/codegen/organize_query_hooks.py\n\n")
        for line in sorted(index_lines):
            f.write(line + "\n")

    print(f"\nOrganized {len(index_lines)} hook files → {SOURCE}")

if __name__ == "__main__":
    main()
