/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Vyzorix Update Server API
 * Go-generated OpenAPI contract from handler annotations
 * OpenAPI spec version: 0.0.01
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChannelStatusResult,
  ChannelSubscribeRequest,
  ChannelSubscribeResult,
  ChannelUnsubscribeResult,
  ErrorResponse,
  PostChannelsUnsubscribeParams
} from '../../../../../@vyzorix/api-client/generated/schemas';

import { customAxios } from '../../../../../packages/API_Client/src/generated/rest-bridge';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetChannelsStatusUrl = () => {




  return `/channels/status`
}

/**
 * Returns active channel streams for the org
 * @summary Channel status
 */
export const getChannelsStatus = async ( options?: Parameters<typeof customAxios>[1]): Promise<ChannelStatusResult> => {

  return customAxios<ChannelStatusResult>(getGetChannelsStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetChannelsStatusQueryKey = () => {
    return [
    `/channels/status`
    ] as const;
    }


export const getGetChannelsStatusQueryOptions = <TData = Awaited<ReturnType<typeof getChannelsStatus>>, TError = ErrorResponse>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannelsStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChannelsStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannelsStatus>>> = ({ signal }) => getChannelsStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChannelsStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetChannelsStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getChannelsStatus>>>
export type GetChannelsStatusQueryError = ErrorResponse


/**
 * @summary Channel status
 */

export function useGetChannelsStatus<TData = Awaited<ReturnType<typeof getChannelsStatus>>, TError = ErrorResponse>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannelsStatus>>, TError, TData>, request?: SecondParameter<typeof customAxios>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetChannelsStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostChannelsSubscribeUrl = () => {




  return `/channels/subscribe`
}

/**
 * Registers a logical subscription to a channel scope for the operator
 * @summary Subscribe to channel
 */
export const postChannelsSubscribe = async (channelSubscribeRequest: ChannelSubscribeRequest, options?: Parameters<typeof customAxios>[1]): Promise<ChannelSubscribeResult> => {

    const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customAxios<ChannelSubscribeResult>(getPostChannelsSubscribeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(channelSubscribeRequest)
  }
);}





export const getPostChannelsSubscribeMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsSubscribe>>, TError,{data: ChannelSubscribeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postChannelsSubscribe>>, TError,{data: ChannelSubscribeRequest}, TContext> => {

const mutationKey = ['postChannelsSubscribe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannelsSubscribe>>, {data: ChannelSubscribeRequest}> = (props) => {
          const {data} = props ?? {};

          return  postChannelsSubscribe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostChannelsSubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof postChannelsSubscribe>>>
    export type PostChannelsSubscribeMutationBody = ChannelSubscribeRequest
    export type PostChannelsSubscribeMutationError = ErrorResponse

    /**
 * @summary Subscribe to channel
 */
export const usePostChannelsSubscribe = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsSubscribe>>, TError,{data: ChannelSubscribeRequest}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postChannelsSubscribe>>,
        TError,
        {data: ChannelSubscribeRequest},
        TContext
      > => {
      return useMutation(getPostChannelsSubscribeMutationOptions(options));
    }
    export const getPostChannelsUnsubscribeUrl = (params: PostChannelsUnsubscribeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/channels/unsubscribe?${stringifiedParams}` : `/channels/unsubscribe`
}

/**
 * Removes a logical subscription to a channel scope
 * @summary Unsubscribe from channel
 */
export const postChannelsUnsubscribe = async (params: PostChannelsUnsubscribeParams, options?: Parameters<typeof customAxios>[1]): Promise<ChannelUnsubscribeResult> => {

  return customAxios<ChannelUnsubscribeResult>(getPostChannelsUnsubscribeUrl(params),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostChannelsUnsubscribeMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsUnsubscribe>>, TError,{params: PostChannelsUnsubscribeParams}, TContext>, request?: SecondParameter<typeof customAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postChannelsUnsubscribe>>, TError,{params: PostChannelsUnsubscribeParams}, TContext> => {

const mutationKey = ['postChannelsUnsubscribe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannelsUnsubscribe>>, {params: PostChannelsUnsubscribeParams}> = (props) => {
          const {params} = props ?? {};

          return  postChannelsUnsubscribe(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostChannelsUnsubscribeMutationResult = NonNullable<Awaited<ReturnType<typeof postChannelsUnsubscribe>>>

    export type PostChannelsUnsubscribeMutationError = ErrorResponse

    /**
 * @summary Unsubscribe from channel
 */
export const usePostChannelsUnsubscribe = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsUnsubscribe>>, TError,{params: PostChannelsUnsubscribeParams}, TContext>, request?: SecondParameter<typeof customAxios>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postChannelsUnsubscribe>>,
        TError,
        {params: PostChannelsUnsubscribeParams},
        TContext
      > => {
      return useMutation(getPostChannelsUnsubscribeMutationOptions(options));
    }
