// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"time"

	keys "github.com/VinnsEdesigner/vyzorix/apps/api/internal/application/keys"
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/config"
	infranotification "github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/notification"
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/storage"
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/webhook"
)

// Injectors from wire_gen.go:

// Injector creates all dependencies.
func Injector(cfg config.Config) (*Server, error) {
	logger := ProvideLogger()
	sqLite, err := ProvideSQLite(cfg)
	if err != nil {
		return nil, err
	}
	db := ProvideDB(sqLite)
	auditLogger := ProvideAuditLogger(db, logger)
	manager := ProvideSessionManager(cfg)
	verifier := ProvideGoogleVerifier(cfg)
	operatorRepository := ProvideOperatorRepository(db)
	deviceRepository := ProvideDeviceRepository(db)
	eventRepository := ProvideEventRepository(db)
	commandRepository := ProvideCommandRepository(db)
	sessionRepository := ProvideSessionRepository(db)
	clientRepository := ProvideClientRepository(db)
	telemetryRepository := ProvideTelemetryRepository(db)
	updatesStorage := ProvideUpdatesStorage(db)
	emailVerificationRepository := ProvideEmailVerificationRepository(db)
	passwordResetRepository := ProvidePasswordResetRepository(db)
	argon2idHasher := ProvidePasswordHasher()
	authService := ProvideAuthService(operatorRepository, sessionRepository, emailVerificationRepository, passwordResetRepository, argon2idHasher)
	service := ProvideDeviceService(deviceRepository, operatorRepository, logger)
	clientService := ProvideClientService(clientRepository)
	commandService := ProvideCommandService(commandRepository, deviceRepository)
	emailService := ProvideEmailService()
	metrics := ProvideMetrics()
	hubResult := ProvideWebSocketHub(logger, deviceRepository, telemetryRepository, db)
	notifier := ProvideFCMNotifier(logger, cfg)
	middlewareFactory := ProvideMiddlewareFactory(logger, manager, authService, clientService, cfg)
	rateLimiter := ProvideRateLimiter()
	lockout := ProvideLockout()
	ipIntelligence := ProvideIPIntelligence(middlewareFactory)
	updatesService := ProvideUpdatesService(updatesStorage, service, hubResult, notifier, commandService, logger, cfg)
	// Create webhook client for notifications
	webhookClient := ProvideWebhookClient()
	// Create notification repository for audit logging
	notificationRepository := ProvideNotificationAuditRepository(db)
	// Create notification service
	notificationService := ProvideNotificationService(operatorRepository, emailService, webhookClient, notificationRepository, logger)
	// Create event processor and wire notification service
	eventProcessor := ProvideEventProcessor(eventRepository, deviceRepository, operatorRepository, hubResult, logger)
	WireNotificationServiceToProcessor(eventProcessor, notificationService)
	apiKeyRepository := ProvideAPIKeyRepository(db)
	apiKeyService := ProvideAPIKeyService(apiKeyRepository, cfg)
	serverDependencies := ProvideServerDependencies(cfg, logger, sqLite, auditLogger, manager, verifier, operatorRepository, deviceRepository, commandRepository, sessionRepository, clientRepository, telemetryRepository, updatesStorage, emailVerificationRepository, passwordResetRepository, argon2idHasher, authService, service, clientService, commandService, emailService, metrics, hubResult, notifier, middlewareFactory, rateLimiter, lockout, ipIntelligence, updatesService, apiKeyService)
	serverResult := ProvideServerResult(serverDependencies)
	server := ProvideServer(serverDependencies, serverResult)
	return server, nil
}

// ProvideWebhookClient creates a webhook client for notifications.
func ProvideWebhookClient() *webhook.Client {
	return webhook.NewClient(10 * time.Second)
}

// ProvideNotificationAuditRepository creates the notification audit repository.
func ProvideNotificationAuditRepository(db *sql.DB) *infranotification.Repository {
	return infranotification.NewRepository(db)
}

// ProvideAPIKeyRepository provides the API key repository.
func ProvideAPIKeyRepository(db *sql.DB) storage.APIKeyRepository {
	return storage.NewAPIKeyRepository(db)
}

// ProvideAPIKeyService provides the API key service.
func ProvideAPIKeyService(repo storage.APIKeyRepository, cfg config.Config) *keys.APIKeyService {
	return keys.NewAPIKeyService(repo, keys.Config{
		Prefix:            cfg.APIKeyPrefix,
		MaxPerMonth:       cfg.MonthlyKeyLimit,
		MaxNameLength:     cfg.MaxKeyNameLength,
		DefaultExpiryDays: 0,
		MaxExpiryDays:     365,
		PrefixLength:      8,
	})
}
