// Package wire provides dependency injection using google/wire.
// This file is generated by wire. DO NOT EDIT.

//go:build wireinject

package wire

import (
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/config"
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/storage"
)

// Injector is the main injector function that wire will implement.
// This is a placeholder - wire gen does not fully work with this project.
func Injector(cfg config.Config) (
	*storage.SQLite,
	*storage.OperatorRepository,
	*storage.DeviceRepository,
	*storage.CommandRepository,
	*storage.SessionRepository,
) {
	panic("unimplemented: wire will generate this")
}
