// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/VinnsEdesigner/vyzorix/apps/api/internal/infrastructure/config"
)

// Injectors from wire_gen.go:

// Injector creates all dependencies.
func Injector(cfg config.Config) (*Server, error) {
	logger := ProvideLogger()
	sqLite, err := ProvideSQLite(cfg)
	if err != nil {
		return nil, err
	}
	db := ProvideDB(sqLite)
	auditLogger := ProvideAuditLogger(db, logger)
	manager := ProvideSessionManager(cfg)
	verifier := ProvideGoogleVerifier(cfg)
	operatorRepository := ProvideOperatorRepository(db)
	deviceRepository := ProvideDeviceRepository(db)
	commandRepository := ProvideCommandRepository(db)
	sessionRepository := ProvideSessionRepository(db)
	clientRepository := ProvideClientRepository(db)
	telemetryRepository := ProvideTelemetryRepository(db)
	updatesStorage := ProvideUpdatesStorage(db)
	emailVerificationRepository := ProvideEmailVerificationRepository(db)
	passwordResetRepository := ProvidePasswordResetRepository(db)
	argon2idHasher := ProvidePasswordHasher()
	authService := ProvideAuthService(operatorRepository, sessionRepository, emailVerificationRepository, passwordResetRepository, argon2idHasher)
	service := ProvideDeviceService(deviceRepository, operatorRepository)
	clientService := ProvideClientService(clientRepository)
	commandService := ProvideCommandService(commandRepository, deviceRepository)
	emailService := ProvideEmailService()
	metrics := ProvideMetrics()
	hubResult := ProvideWebSocketHub(logger, deviceRepository, telemetryRepository, db)
	notifier := ProvideFCMNotifier(logger, cfg)
	middlewareFactory := ProvideMiddlewareFactory(logger, manager, authService, clientService, cfg)
	rateLimiter := ProvideRateLimiter()
	lockout := ProvideLockout()
	ipIntelligence := ProvideIPIntelligence(middlewareFactory)
	serverDependencies := ProvideServerDependencies(cfg, logger, sqLite, auditLogger, manager, verifier, operatorRepository, deviceRepository, commandRepository, sessionRepository, clientRepository, telemetryRepository, updatesStorage, emailVerificationRepository, passwordResetRepository, argon2idHasher, authService, service, clientService, commandService, emailService, metrics, hubResult, notifier, middlewareFactory, rateLimiter, lockout, ipIntelligence)
	serverResult := ProvideServerResult(serverDependencies)
	server := ProvideServer(serverDependencies, serverResult)
	return server, nil
}
